### ISSUE TITLE
include pre-commit config

### ISSUE THREAD

**Issue by ryanrhee** [bufbuild/buf#1077]
same as https://github.com/bufbuild/buf/issues/340 ;

[pre-commit](https://github.com/pre-commit/pre-commit) has almost double the number of stars as buf (7.9k vs 4.1k at the time of writing),  so i'm a bit surprised it was written off as having not enough usage.

I'm asking the buf team to please reconsider setting up an officially supported pre-commit hook in the repo.

Thank you for your consideration.

**Comment by bufdev** [comment]
Feel free to put up a PR for it, we can consider it - I'd like to see exactly what we're proposing, as we're not familiar with pre-commit:

- Are there separate hooks for lint, breaking, other actions?
- How to do configuration?
- What do we have to do in terms of maintenance?
- Does this have to live in bufbuild/buf?

**Comment by asottile** [comment]
I was asked by ryan to throw some thoughts here -- hope this is helpful!  (@-mention me directly if you need clarification since I'll have muted)

>     * Are there separate hooks for lint, breaking, other actions?

it could be as many or as few makes sense for consumers -- though it's also flexible (consumers can override the arguments / options directly via `args` or `entry`)

>     * How to do configuration?

in ~theory configuration should work the same as it does for other users -- though there would be a tiny bit of config that a consumer would use to reference your repository (and any `args` they would want to customize there) -- it'd look something like:

```yaml
-   repo: https://github.com/bufbuild/buf
    rev: ...
    hooks:
    -   id: buf-validate  # or whatever the hook entry id is called!
```

>     * What do we have to do in terms of maintenance?

most integrations require zero maintenance after the initial commit -- though I think either ryan or I would be happy to field questions / support for this

>     * Does this have to live in bufbuild/buf?

it's usually easiest for consumers if the small yaml file ends up here (they know where to go for documentation, etc. and there won't need to be additional moving parts for releases / etc.).  a "mirror repo" can be set up, but it's a significantly worse experience for consumers

hope this clarifies things!

anthony

**Comment by bufdev** [comment]
We're happy to consider it, but it's not something we can prioritize. We're happy to consider a PR though. Adding to wishlist for our own tracking.

**Comment by ryanrhee** [comment]
Understood. I will put up a PR.

Is there a way to have invocations of `buf` use filenames as opposed to directories containing `buf.yaml` or `buf.work.yaml` files? i didn't see anything when i skimmed the docs, but i wanted to make sure.

**Comment by amckinney** [comment]
> to clarify, i'm wondering if there's a way to ask buf to figure out which config to run given a file, rather than having it use a config to figure out which files to run on.

Yes, `buf` works with single file inputs, but it's not the technique we evangelize - `buf` firmly believes that `.proto` should be thought of in terms of directories and packages instead.

But with all that said, you can still run commands like the following:

```sh
$ buf build ./proto/acme/pet/v1/pet.proto
```

`buf` will ascend the file's parent directories until it either finds a `buf.yaml` or a `buf.work.yaml` to which to base the file's import paths.

After reviewing the input docs I linked above, it looks like we'll need to add some documentation for this behavior. I'll open another issue for that in the relevant repository - thanks!

**Comment by ryanrhee** [comment]
@amckinney thanks for the clarification. I think what you're referring to is a single `.proto` file; can buf execute the same logic but for multiple `.proto` files? e.g.:

```console
$ buf lint ./proto/acme/pet/v1/pet.proto ./proto/acme/foo/v1/bar.proto
```

where `./proto/acme/pet/buf.yaml` and `./proto/acme/foo/buf.yaml` are separate?

**Comment by ryanrhee** [comment]
> are you working on supporting `buf format` by any chance?

I'm focusing on `buf lint` first. I plan on doing `format` afterwards.

**Comment by lrewega** [comment]
We discussed in Slack, but for posterity: I'd suggest following how golangci-lint does it: https://github.com/golangci/golangci-lint/blob/master/.pre-commit-hooks.yaml

**Comment by ryanrhee** [comment]
@arturdryomov fyi I did end up including `buf format` in my PR.

**Comment by bufdev** [comment]
This is added from #1182, is available on `main`, and will go out in the next release.
