### ISSUE TITLE
buf lint stat error 

### ISSUE THREAD

**Issue by lmolas** [bufbuild/buf#1086]
If you have an import proto path like this: /license/api.proto and you have a license file in another module, a stat error "not a directory" appears:
Failure: stat {omitted path}/license/api.proto: not a directory

In the code you only continue if you encounter "not exists" errors.
But "not a directory" error breaks.

**Comment by bufdev** [comment]
For us to look into this, you must provide exact reproduction steps.

**Comment by lmolas** [comment]
[buf-issue.tar.gz](https://github.com/bufbuild/buf/files/8571022/buf-issue.tar.gz)

As explained in the README, just run buf lint.

**Comment by bufdev** [comment]
@amckinney 

The issue is here: https://github.com/bufbuild/buf/blob/14ed91784fcd5cd06763c420ce6d765092571430/private/buf/buffetch/internal/reader.go#L807 this is getting triggered if you have:

```
├── buf.work.yaml
├── module1
│   └── license
│       └── v1
│           ├── api.proto
│           └── core.proto
└── module2
    ├── dummy
    │   └── v1
    │       └── dummy.proto
    └── license
```

`module1/license` is a directory, but `module2/license` is not. If you rename `module2/license` to `module2/license2`, there is no issue. You might know right away what is going on here.

**Comment by amckinney** [comment]
Thanks for the issue @lmolas! This will go out in the next release.

**Comment by lmolas** [comment]
Thanks for the quick fix
