### ISSUE TITLE
Ignore nested buf.yaml during generate

### ISSUE THREAD

**Issue by hexfusion** [bufbuild/buf#1095]
My project has a git submodule that contains proto definitions and is also managed by buf thus it has a buf.yaml. When I run buf generate it consumes that config while is not what I want. I looked through the docs and could not find an option to ignore this.

```
buf.yaml
git-submodule/proto/
├── foo
│   └── foo.proto
├── bar
│   └── bar.proto
├── buf.gen.yaml
├── buf.lock 
├── buf.yaml < -- excludes bar/
```

Ideally I would like a global bool or the option to skip explicit configs. Outside of removing the file is there a workaround?

```
version: v1
build:
  exclude-nested-config: true
```

**Comment by amckinney** [comment]
The git submodule's `proto` directory should be thought of as its own independent module - if `git-submodule/proto/buf.yaml` specifies that `bar` should be excluded, then that's how the module ought to be consumed.

It doesn't make much sense to add a `exclude-nested-config` option to the `buf.yaml` because the `buf.yaml` doesn't have a notion of nested `buf.yaml` configurations - it's just a single, independent module. In other words, having a `buf.yaml` at the root of your repository that references a nested `buf.yaml` probably isn't what you want.

Instead, you can just override the configuration value you want to use with the `--config` flag. So rather than adding an explicit `exclude_nested_config`, just do something like the following:

```sh
$ buf generate git-submodule/proto --config '{"version": "v1"}'
```

or

```sh
$ buf generate git-submodule/proto --config path/to/buf.yaml
```

In the above case, the `path/to/buf.yaml` wouldn't exclude the `bar` directory (for example).

Make sure to check out [workspaces](https://docs.buf.build/reference/workspaces) (defined with a `buf.work.yaml`) - they let you join multiple modules together into a single buildable unit, so that might be useful to you later on.
