### ISSUE TITLE
How do I build proto files of a submodule that contains no buf.yaml

### ISSUE THREAD

**Issue by buehler** [bufbuild/buf#1103]
Hey there

The case I'm trying to solve involves an external repository to which I have no contribution access. I want to build proto files from that repository and they have several external dependencies. Sadly in `buf.work.yaml` I cannot define dependencies. And in the external repository, I cannot add a `buf.yaml` because that would "dirty" the submodule.

Is there a way to define the directory in question without having to copy paste the files around?

**Comment by buehler** [comment]
Maybe I understand the use-case of "buf" in a wrong way. I'd love it, if I'd be able to generate code for a list of proto files. But _even_ a list of files that I don't own.

For example:
I want to generate a grpc client for https://github.com/zitadel/zitadel/tree/main/proto/zitadel. But since they have a dependency to googleapis, protoc-gen-validate and openapiv2 (grpc-gateway), I'm not able to just include that directory. I need to _download_ all protos (or link them as git submodules) to have all needed proto files. Only then, I'm able to generate with buf. So the only thing that buf removes is to manually build the protoc command.

It would be a big improvement if I could define a list of proto files with the required dependencies. (Since I'm not able to put a buf.yaml file into the submodule)

**Comment by amckinney** [comment]
Thanks for the issue @buehler, this is one a good one for us to consider. Just to be clear, `buf` doesn't actually invoke `protoc` at all - it has its own [internal compiler](https://docs.buf.build/reference/internal-compiler). 

## Problem

Like you've already described, `buf` will only use the `buf.yaml` or `buf.work.yaml` associated with the _input_ - adding a dependency to your `buf.work.yaml` won't do anything if you're generating a remote input like the following:

```sh
$ buf generate https://github.com/zitadel/zitadel.git#subdir=proto
```

To be clear, the `buf.work.yaml` wouldn't have been used because it's not discoverable from the remote reference (it's a file on your local filesystem, which isn't the input that you're linting).

You can normally get this type of behavior with a `--config` override - just specify the configuration you'd like to use against the input, and it'll be used. You can either use a `.yaml` file that you write somewhere, or write the JSON equivalent in-line:

```sh
$ buf generate https://github.com/zitadel/zitadel.git#subdir=proto --config '{"version": "v1", "build": {"excludes": ["foo"]}'
```

However, `buf` won't let you include the dependencies you specify in your `buf.yaml` - a `buf.lock` needs to exist for the dependencies to be included. For example,

```sh
$ buf generate https://github.com/zitadel/zitadel.git#subdir=proto --config '{"version": "v1", "deps": ["buf.build/grpc-ecosystem/grpc-gateway"]}'
WARN	Specified deps are not covered in your buf.lock, run "buf mod update":
	- buf.build/grpc-ecosystem/grpc-gateway
proto/zitadel/object.proto:4:8:proto/protoc-gen-openapiv2/options/annotations.proto: does not exist
```

## (Potential) Solutions

We could solve this by:

1. Add a new configuration option to the `buf.work.yaml` to specify remote dependencies and add a `--workspace` flag that lets you include the workspace in your build.

```yaml
# buf.work.yaml
version: v1
directories:
  - foo
  - bar
remotes:
  - buf.build/grpc-ecosystem/grpc-gateway
```

```sh
$ buf generate https://github.com/zitadel/zitadel.git#subdir=proto --workspace buf.work.yaml
```

2. Add a new flag that resolves and includes the dependencies specified in the `buf.yaml` without a `buf.lock` (e.g. `--include-deps`).

```sh
$ buf generate https://github.com/zitadel/zitadel.git#subdir=proto --config '{"version": "v1", "deps": ["buf.build/grpc-ecosystem/grpc-gateway"]}' --include-deps
```

--

Each option has some pros and cons - (1) expands the scope of what a `buf.work.yaml` is meant to be used for, and (2) requires that you specify a custom `buf.yaml` that you want to use for any given input. We'll need to think about which one makes the most sense in the long run, so it might be a little while before you see a good solution to your problem.

## Workaround

In the meantime, you can create a `buf.work.yaml` at the root of your repository, and include a directory for each of your dependencies:

```yaml
version: v1
directories:
  - zitadel/proto # your git sub module
  - protoc-gen-openapiv2
  - protoc-gen-validate
```

Then you can write a simple script to keep everything up to date (based on what's published in the BSR), with a few `buf export` commands:

```sh
# Remote the workspace directories to get a clean build ...
# ...
buf export buf.build/grpc-ecosystem/grpc-gateway -o protoc-gen-openapiv2
buf export buf.build/envoyproxy/protoc-gen-validate -o protoc-gen-validate
```

By omitting the `:<commit>` suffix, the `buf export` command will always write the latest content of the module into the directory that you specify.

**Comment by buehler** [comment]
Thank you for the thorough explanation! I'm definitely looking forward to this. In my opinion, it will generate more traction for the tool if it is usable to just generate clients for remote proto repositories.

Thank you for the workaround, I will try one of these solutions you mentioned.
