### ISSUE TITLE
Filtering images by type is nondeterministic

### ISSUE THREAD

**Issue by mfridman** [bufbuild/buf#1183]
In https://github.com/bufbuild/buf/pull/949 we added the ability to create filtered images containing only the specified types and their required dependencies.

The issue is some consumers require deterministic output. Example from [public slack](https://bufbuild.slack.com/archives/CRZ680FUH/p1654656935483599):

> Hello there. I’m using buf to build binary proto descriptors to inject into
envoy’s grpc-json transcoding filter. When it inspects the descriptors it seems
to want things to be ordered by dependencies so it doesn’t have to read the
next thing to validate the current thing which feels fair.

> If I filter my output using --type the order of the protos in the descriptor
set changes and fails envoy validation.

Based on this comment we knew this was going to be the case. Let's discuss if we want to fix this.

https://github.com/bufbuild/buf/blob/102100e61f95173ce323f47a64ef34f1d706eb98/private/bufpkg/bufimage/bufimageutil/bufimageutil.go#L169-L171

**Comment by bufdev** [comment]
I think we definitely want to fix this if it's feasible in a short amount of time - there is almost for sure some kind of sort we can do right? Often it just means tldr keeping a `[]string` alongside your `map[string]whatever`.

**Comment by robbertvanginkel** [comment]
When I was writing this code thinking about just the types, DAG ordering isn't always possible on a type level since types can have circular references. However, since the types are still outputted in their original (but trimmed down) files we should still be able to sort the files in dependency order.

Using the `reorder` in https://github.com/bufbuild/buf/blob/852c2ed5c1f410686e668695423376466a753bc5/private/bufpkg/bufimage/image.go#L29 should fix this.
