### ISSUE TITLE
why set protoc version to unknown

### ISSUE THREAD

**Issue by yusank** [bufbuild/buf#1244]
`protoc` version shouldn't set as unknown in any circumstance. Versions are make sure to find problem ASAP and navigate to a unique commit. I'm not getting It's a bug or a feature ,can you please at least add some options to write which version of prooc into 
 generated files instead of generate code with unknown version like this :

```go
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: config/v1/config.proto
```

**Comment by amckinney** [comment]
See my reply [here](https://github.com/bufbuild/buf/issues/799#issuecomment-996881066).

In summary, `protoc` wasn't used to compile your Protobuf code at all - `buf` has its own [internal compiler](https://docs.buf.build/reference/internal-compiler). Any version we include in the `protoc` space would be inaccurate. Sure, we could use the `buf` version, but that would be _more_ confusing because `protoc` wasn't involved at all.
