### ISSUE TITLE
format command doesn't work on windows where diff exe isn't installed

### ISSUE THREAD

**Issue by paul-sachs** [bufbuild/buf#1251]
The command buf format currently fails if the host does not have a diff command on PATH. This means that the format command (and associated vscode plugin) will fail on windows.

Env:
- Windows 11
- Powershell 7

```bash
buf format
```

Outputs:

```bash
Failure: exec: "diff": executable file not found in %PATH%
```

**Comment by doriable** [comment]
I looked into reproducing this and was able to run `buf format -d` on my Windows machine.
Looking into this, it seems that `diff` is an alias in Powershell for `Compare-Object`, and should be set out of the box.

```
PS > Get-Alias diff                                                                                                                                                                                                                                                                                                    CommandType     Name                                               Version    Source                                                                                        -----------     ----                                               -------    ------                                                                                        Alias           diff -> Compare-Object     
```

I ran this on both Powershell 5.1 and 7 and did not run into any issues for `buf format -d`.
The `buf` version I used was `v1.6.0`.
Going to close this issue for now and am happy to answer any follow-ups to this.

**Comment by rofrankel** [comment]
Yep, I have that alias set.  I don't have an explanation for why I get this error despite the alias.  But I can still repro it.  Is there something I can do to help debug?

**Comment by DoItWithASmile** [comment]
@rofrankel did u ever find a solution?

I am running into the same issue with Windows 11.

My workaround:
create a `diff.bat` with the content of
`powershell -command "Compare-Object %*"`
located in the PATH environment variable

This redirects it to powershell, the error goes away and formatting works like charm.

And yes, powershell has the alias! The issue seems that VS Code or `buf` is not calling powershell as command prompt, but `CMD.exe`.

I searched for a solution on how this can be changed. I came up empty. I remember vaguely that I changed the default console app somehow years ago. Maybe that is just a false memory though...

As a developer, it makes me curious: is the command line execution environment not explicitly set when running `buf format`? `diff` clearly is only available in PowerShell and not in other environments.

Btw, even VS Code detects multiple different command line environments. In my case for example the one from Visual Studio (which calls CMD.exe as well, not PowerShell) and others.

**Comment by SamJaarsma** [comment]
Add set PATH=%PATH%;c:\Program Files\Git\usr\bin

or more permanent: add the path of diff.exe to the PATH environment variable via the Control Panel.

![image](https://github.com/bufbuild/buf/assets/122641111/7e85c03f-e968-464b-b348-fa3ec91dc58b)
