### ISSUE TITLE
Not possible to nest protos in versioned package

### ISSUE THREAD

**Issue by jacobkristhammarsinch** [bufbuild/buf#132]
Hey!

`PACKAGE_VERSION_SUFFIX` requires the version to be the last segment in a package name.

Sometimes it's desirable to organize multiple protos, all on the same strict version, into subfolders.

This currently breaks this rule. Wouldn't it make sense to only require a version to be part of any package segment and not enforce that it's last?

Example:
```
foo/bar/v1alpha1/resources/baz.proto:3:1:Package name "foo.bar.v1alpha1.resources" should be suffixed with a correctly formed version, such as "foo.bar.v1alpha1.resources.v1".
```

**Comment by johanbrandhorst** [comment]
Hey, thanks for your interest in the project! This is an alternative version management scheme, and we're currently recommending a set of opinionated style guides with minimal developer flexibility and configuration. The main reason for this is the value that can be gained in having uniform standards across the whole community. The granular versioning scheme may be overly specific for some use cases, but it means that when you see another code base following the same style guide, everything will be laid out the way you're used to. We're explicitly requiring each package to be versioned independently because it allows them to evolve independently rather than as a group, which becomes much harder to manage.

**Comment by jacobk** [comment]
Thanks for the answer! I empathize with this sentiment but I'm skeptical it has the desired result if codebases are pushed to disable rules as the only means to gain _some_ flexibility. In this specific case, I challenge the logic in enforcing each package to be versioned rather than groups of protos (while still enforcing _a_ package to be versioned). 

It only means I'm pushed to put all (potentially many) protos in a flat structure instead of providing some sensible directory structure.

Our current proto structure models services, all on a strict version, consisting of a set of protos. Individual "sub" protos will never be allowed to have a different version than the containing package (as already included in its package path). 

I also find it odd if you suggest we should have packages like `foo.bar.v1.resources.v2`. I'm not even sure how to interpret a package path like that.

> We're explicitly requiring each package to be versioned independently because it allows them to evolve independently rather than as a group, which becomes much harder to manage.

In our setting (and also google cloud endpoints etc.) this becomes counter-productive since that's the exact guarantee we wish to provide - that no proto, in a set of related (for a given service) protos ever change in a way to changes the semantics of the group.

> The main reason for this is the value that can be gained in having uniform standards across the whole community.

I would love for such a standard to emerge, but this rule seems very impractical to me.

Currently, there are almost 9000 occurrences of packages with sub-packages after the version designator in https://github.com/googleapis/googleapis/tree/master/google

**Comment by bufdev** [comment]
This is actually a standard:

- googleapis (that you link above) uses version suffixes for the vast majority of its APIs
- https://github.com/lyft/clutch/tree/main/api
- https://github.com/uber/prototool/tree/dev/style#package-versioning
- https://google.aip.dev/215
- https://google.aip.dev/191

We wouldn't recommend doing `foo.bar.v1.resources.v2` - we're not sure how to interpret this either, and we wouldn't recommend doing this. The package version is meant so you can iterate on packages independently.

What you're asking for is a linter that checks that a single component of a package is a valid version, i.e. as long as `num_versions_in(split("foo.bar.v1.baz", ".")) == 1`, then the linter passes. This will lead to further inconsistency in the Protobuf ecosystem, and doesn't add much value. We (along with others across the Protobuf ecosystem) find package suffixes to be very sensible and the right call for the vast majority of users.

If you would like to disregard this lint rule, you can just disable it, but we don't see ourselves adding the above proposed lint rule.

**Comment by jacobk** [comment]
Thanks for the comprehensive answer!

I like that https://google.aip.dev/191 is clear wrt "APIs defined in protocol buffers must define each individual API in a **single package**...". Since I don't have any interest in diverging from established conventions I think that's acceptable (I based my statement above on looking at the available protos in the googleapis repo).

With that said, do you have a good summary/rationale for this "single" package rule, as opposed to allowing a single versioned package, with sub-packages for structure? This would be a great addition to the docs. I agree with everything in https://buf.build/docs/lint-checkers#package_version_suffix but I fail to see how nesting dirs under the versioned package fundamentally breaks this.

Does a multi-package layout complicate the distribution of stubs etc. down the line?
