### ISSUE TITLE
Buf doesn't recognise "v0" as a valid version

### ISSUE THREAD

**Issue by negram** [bufbuild/buf#1335]
In our company, we have a standard that version "zero" (v0) is a development branch however, `buf` only accepts positive numbers as a version suffix.

Basically, a typical proto-file looks like this:
```proto
syntax = "proto3";

package bumble.xapi.recommender.v0;
```

But when we run `buf lint` against it, we will get:
```
recommender.proto:3:1:Package name "bumble.xapi.recommender.v0" should be suffixed with a correctly formed version, such as "bumble.xapi.recommender.v0.v1".
```

I can understand why it is so, I just wanted to check if there's anything we could do about it. Maybe add a specific option for `buf`. Or that rule about "positive number" might be not that strict.

What are your thoughts?

**Comment by amckinney** [comment]
I know you've said that you already understand, but I'll include the reasoning for posterity - the [`PACKAGE_VERSION_SUFFIX`](https://docs.buf.build/lint/rules#package_version_suffix) rule suggests that such unstable, in-development packages should actually be packages suffixed with `alpha1`, or something similar (e.g. `v1alpha1`), instead of `v0`.

> Maybe add a specific option for buf. Or that rule about "positive number" might be not that strict.

Both of your suggestions are technically reasonable, but there are some caveats. The `PACKAGE_VERSION_SUFFIX` rule would become _more_ permissive, but some organizations might actually depend on the fact that it prevents users from using the `v0` suffix (they might want that version to be outlawed, for example). So although it feels like a backwards compatible change, it would potentially break certain use cases.

In this case, we'd need to add a new configuration option to the `buf.lint` configuration key, or build out a new lint rule that you can configure (e.g. `PACKAGE_VERSION_SUFFIX_WITH_ZERO` - that might not be the name we'd actually go with, but you get the idea).

 With all that said, we _could_ implement one of these features, but I'd rather encourage you to adopt the standard package versioning structure that we're promoting. One of Buf's primary goals is to make Protobuf consistent everywhere, and that's exactly what the `DEFAULT` set of lint rules helps us achieve. The more differences we accommodate, the more frequent there will be differences.

What are your thoughts?

**Comment by amckinney** [comment]
I'll close this as-is - we likely won't get around to this one.

**Comment by nemith** [comment]
Buf documentation actually lists v0 as recommendation for unstable apis  https://buf.build/docs/reference/protobuf-files-and-packages#packages

Probably should match the documentation with the lint expectations?

**Comment by nemith** [comment]
I think `v0` (no guarantees on api stability) is different than `alpha`  or `beta`.   You can compare this to the equivelent v0 scheme used for Go which does the same.    I would agree that `v0` shouldn't be default but it's small and susinct and implies different intentions than an alpha or or beta moniker. 

I also disagree that a lint change is a breaking rule.  I think that is a bit of a stretch in reasoning.  

So i think this is unfortunate but understandable.
