### ISSUE TITLE
Skip BC checking for packages with 'beta' or 'alpha' in name

### ISSUE THREAD

**Issue by kostyay** [bufbuild/buf#140]
Hey
Is it possible to disable BC checking for packages that are named as `v1beta1`.. since its ok for those APIs to make breaking changes.

Thanks

**Comment by bufdev** [comment]
We didn't want to add special-cased naming like this to rules, but this is something we can consider.

**Comment by bufdev** [comment]
I think we're not going to do this one - you can ignore directories already, and we *really* don't want to add special-casing for naming. If there's another general solution at some point, feel free to comment!

**Comment by Fleshgrinder** [comment]
But ignoring the directories means that all other lint rules are also not applied to the files within those directories. The inability to enforce everything except breaking change detection is something that is very important while a new service is being introduced.

**Comment by bufdev** [comment]
Lint rule ignores and breaking rule ignores are separate. What's the concern here?

**Comment by Fleshgrinder** [comment]
I guess there are two ways to solve my concern:

1. Fixed rules to ignore packages with those special pre-release identifiers.
1. Support for some kind of patterns in [ignore](https://docs.buf.build/breaking-configuration#ignore) (ext- + star glob, re2, …)

Currently it would be necessary to add a line for each single directory that needs to be ignored, which can grow very fast if one has many schemas and become a nightmare to manage because we know that humans will forget to remove the rule for their directory once they move out of the pre-release phase. Of course we could now use another tool to lint the buf configuration but that leads to total linter inception. 😝 

```yaml
breaking:
  ignore:
    - **/v[1-9]*([0-9]){alpha,beta}?([1-9]*([0-9]))/
```

**Comment by bufdev** [comment]
You know what, it's Friday - we'll do this. We're going to add an option `breaking.ignore_unstable_packages` that defaults to false, that will ignore test, alpha, beta packages as specified in `PACKAGE_VERSION_SUFFIX` https://docs.buf.build/lint-checkers#style_default

**Comment by bufdev** [comment]
See https://github.com/bufbuild/buf/pull/196

**Comment by bufdev** [comment]
This will go out in the next release, we'll update this issue when that happens.

**Comment by bufdev** [comment]
This is released as v0.32.0.

**Comment by kostyay** [comment]
Awesome thanks!

**Comment by unparalleled-js** [comment]
@bufdev It would be valuable to be able to ignore _any_ directory via a pattern instead of just certain special cases.
