### ISSUE TITLE
Support Visibility restriction selectors for `buf build`

### ISSUE THREAD

**Issue by yinzara** [bufbuild/buf#1420]
Google defines a standard set of "visibility selectors" that are used to annotate proto files to allow you to only read from a subset of the protofile when using a plugin that supports visibility selectors.

See
https://github.com/googleapis/googleapis/blob/9916192ab15e3507e41ba2c5165182fec06120d0/google/api/visibility.proto#L89
https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_openapi_output/#hiding-fields-methods-services-and-enum-values

It would be helpful if the `buf build` command supported some kind of `--visibility-selector` argument so that we could output a build that only includes a subset of our proto files.

**Comment by bufdev** [comment]
`buf build` itself is just doing what the compiler would do, it's not meant to be extended to include support for external APIs such as googleapis (protoc wouldn't either). We do care about this problem in general though, and if something is incorporated into `FileDescriptorSet` that performs a similar behavior, we'll definitely add it.

**Comment by sgammon** [comment]
@bufdev could i humbly request a reconsideration of this issue? the logic here of deferring to the compiler is sound (and thank you for enforcing that expectation), but i arrived here w.r.t. a Buf-specific feature.

we want to include some private service definitions in our protos, but we want to avoid pushing them to BSR. we still want to lint them, break check them, and generate from them.

sometimes, there is a method we want to mark as BETA, or PREVIEW, and a label showing up accordingly in BSR (based on this annotation) would be great. it would keep our own docs in sync as well as, potentially, annotations in plugins which throw compiler warnings for experimental methods.

your point is well taken, though, so maybe the request should just be that Buf and BSR can understand these annotations, and when it comes to the rest of your code, you must quite sensibly process them yourself?

i realize this may complicate the code-gen story -- i.e., it would mean that a service with no annotation, that depends on a `INTERNAL` object or `PREVIEW` object, might have to proactively reject such a dependency at build time. otherwise, building with `buf build -o - buf.build/x/y` might break due to missing types.
