### ISSUE TITLE
Generated go code differs between macOS and linux

### ISSUE THREAD

**Issue by BoKleynen** [bufbuild/buf#1725]
When running `buf generate` the generated code has some minor differences in comments with regard to whitespace. I have created a [repository](https://github.com/BoKleynen/buf-minimal-example) with a minimal example to reproduce. 

in https://github.com/BoKleynen/buf-minimal-example/commit/dd63dc3159ab1545044a31f9d95c8b19c1315681 you can see that when running buf generate inside a docker container it adds some whitespace to the comments

**Comment by mfridman** [comment]
Thanks for providing an example! Could this be due to different `go` versions on those machines?

go1.19 had some `gofmt` changes to improve formatting, especially around links, lists and headers ([doc here](https://go.dev/doc/go1.19#go-doc)). There was some relevant [discussion here](https://github.com/golang/go/issues/37974#issuecomment-611088006) with some of those changes (more for background if you're interested).

**Comment by BoKleynen** [comment]
I'm using 1.19 on both

**Comment by mfridman** [comment]
Hey @BoKleynen, plugins based on [`protogen`](https://pkg.go.dev/google.golang.org/protobuf/compiler/protogen) are formatted before the output is returned back to the compiler. E.g.,

https://github.com/protocolbuffers/protobuf-go/blob/31a59208116ee2cacd5b3e4f64cf17ad733e18db/compiler/protogen/protogen.go#L1082-L1084

If the `protoc-` plugin is compiled with go1.18 or go1.19, it'll make a difference in the output due to the changes I linked above. The `buf` CLI does not format the resulting code, so whatever changes you're observing is on the plugin side.

I know you mentioned go1.19 on both machines, but can you please rebuild the plugin binaries themselves, `protoc-gen-go` and `protoc-gen-go-grpc`, on both machines with the same exact version of Go?

---

I checked out the https://github.com/BoKleynen/buf-minimal-example you kindly provided us and ran `buf generate` after installing plugins with go1.18:

```
go install golang.org/dl/go1.18@latest 
go1.18 download
go1.18 install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go1.18 install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
```

The resulting git diff:

```diff
@@ -184,9 +184,9 @@ type StabilityData struct {
 
        // Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
        // doloremque laudantium, totam rem aperiam, eaque ipsa :
-       //   - quae ab illo inventore veritatis et quasi architecto beatae vitae.
-       //   - dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit
-       //     aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui.
+       // - quae ab illo inventore veritatis et quasi architecto beatae vitae.
+       // - dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit
+       //   aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui.
        Filters []string `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
 }
```

If I `rm -rf $GOBIN/protoc-gen-go $GOBIN/protoc-gen-go-grpc`, re-install plugins with go.19, and then `buf generate` there are no changes to the formatting you checked in.

**Comment by BoKleynen** [comment]
Thanks for the reply, I tried again myself and after manually removing the plugins and then reinstalling them, it does indeed work
