### ISSUE TITLE
Error: .cache/buf/v1/module/... symbol XXX already defined at XXX.proto. Only inside a Docker container. 

### ISSUE THREAD

**Issue by zhanjingjie** [bufbuild/buf#1789]
Hello, this is JJ. I'm trying to use Buf to import a third party proto, for example buf.build/googleapis/googleapis.

I have that dependency setup correctly in buf.yaml:
`version: v1
deps:
  - buf.build/googleapis/googleapis
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
  service_suffix: API
  enum_zero_value_suffix: _INVALID`

And after buf mod update, I was able to do "buf build" and "buf generate" without issues locally. I'm able to do them with my local (Mac) installation of Buf through Brew.

But there's an issue with doing "buf mod update" and "buf generate" inside a Docker container. There are many error messages related to the title. 

Could anyone help me with this? Should I configure the Buf module cache location? Or try something else?

**Comment by bufdev** [comment]
You are likely running `buf` from a directory that contains `.cache`, and `buf` is searching within that directory. For example, if you are running from `/`, and you have `/.cache/buf`, then `buf` will also search `.cache/buf`, which you do not want. Things you can do:

- Change your working directory so that `buf` is not run from this context.
- Change the value of `BUF_CACHE_DIR` https://docs.buf.build/bsr/overview#module-cache

**Comment by zhanjingjie** [comment]
Thank you! It worked for me.
