### ISSUE TITLE
Getting error: is outside the context directory

### ISSUE THREAD

**Issue by dharmjit** [bufbuild/buf#18]
Hi, I have a monorepo structure for my project as below
```
├── my-service
│   ├── api
│   ├── buf.yaml
│   ├── cmd
│   └── pkg
├── common
│   ├── optisam
│   └── third_party
├── go.mod
└── go.sum
```

my buf.yaml
```
build:
  roots:
    - api/proto
    - ./../common/optisam/third_party/google
```
and I am getting error **_is outside the context directory_**. I checked this in code and there is a check on **..**. I am not sure why this check is imposed

**Comment by bufdev** [comment]
See https://buf.build/docs/build-configuration#roots

You cannot have a root that points outside of your context, as represented by the location of the `buf.yaml` configuration file, usually at the root of your repository. This is so that you know that everything needed to build the files Buf handles can be found from within this directory, and sub-directories, which is important for breaking change detection, for example. Builds must be self-contained.

**Comment by opticoder** [comment]
@rares-mihai-preda  we are experiencing same issue. Have you found a solution?

**Comment by doriable** [comment]
The `v2` `buf.yaml` configurations encourage putting the `buf.yaml` at the root of your source repository, and you can define all your modules and their roots from there. For example:

```
version: v2
modules:
  - path: folder/proto/api
  - path: folder/proto/common
  # ... etc.
```

Detailed documentation is available here: https://buf.build/docs/configuration/v2/buf-yaml
If you run into any problems, please open a new issue and we can discuss there. Thanks!

**Comment by opticoder** [comment]
Thank you for your reply, @doriable! Your suggestion assumes a monorepo, but our situation is different (and I bet so for the most of others is) - a lot of source repositories for services.
```
repos
├── service1
│   ├── .git
│   ├── api
│   |   └── proto
│   ├── buf.yaml
│   ├── internal
|    ⃛
|   ├── go.mod
|   └── go.sum
├── service2
│   ├── .git
│   ├── api
│   |   └── proto
│   ├── buf.yaml
│   ├── src
|    ⃛
|   ├── package.json
|   └── package-lock.json
└── common
    ├── .git
    ├── proto
    ├── go
    ├── ts
    ├── py
    ├── cxx
     ⃛
```
So there's no way to use
```
modules:
  - path: ../common/proto
```
I looked over the buf sources and I actually don't see the real limitations (including breaking change detection) for using modules outside buf.yaml location. Therefore I conclude that the limitations aren't technical but making users to buy Enterprise subscription for the private BSR feature

**Comment by doriable** [comment]
There are both technical and security concerns around restricting the paths to the configuration context, and this is common/best practices with other types of configuration as well (e.g. Dockerfiles).

> I actually don't see the real limitations (including breaking change detection) for using modules outside buf.yaml location

In the example tree you have provided, you have many repositories, one of which is `common`. If you have a `buf.yaml` defined with a module outside of your source repository, your module will not build when you attempt to run any workflows against your git source repository as an input -- for example a typical breaking change work flow:

```
$ buf breaking --against 'https://github.com/<owner>/service1.git#branch=main'
```

Since the configuration checked into your git source would be unable to resolve a dependency outside its source context. The motivation for this restriction is that one of our guarantees is that we can use git sources as an input, so what you are suggesting would break that guarantee.

If you would like to depend on `common`, our suggestion would be to push it to the BSR, which would not necessitate purchasing our Enterprise offering. We believe in the value the BSR offers, one of which is dependency management for this case, and this is fully available at the free tier. The customers who upgrade to our paid offerings are those who see value in more closely integrating and using the BSR in their day-to-day workflows.

As mentioned, if you have additional concerns about how to configure your use case, please open a new issue, thanks.
