### ISSUE TITLE
Build fails with warning: Could not find remote branch master to clone.

### ISSUE THREAD

**Issue by nitinbhojwani** [bufbuild/buf#186]
I am trying to add buf breaking change detection to the **Bitbucket Pipeline** but it fails with following log lines

```
Unable to find image 'bufbuild/buf:latest' locally
latest: Pulling from bufbuild/buf
df20fa9351a1: Pulling fs layer
d21f2de78f53: Pulling fs layer
082a4f126d02: Pulling fs layer
df20fa9351a1: Verifying Checksum
df20fa9351a1: Download complete
df20fa9351a1: Pull complete
082a4f126d02: Verifying Checksum
082a4f126d02: Download complete
d21f2de78f53: Verifying Checksum
d21f2de78f53: Download complete
d21f2de78f53: Pull complete
082a4f126d02: Pull complete
Digest: sha256:ef4df77d869d8f8ec0bc80a7eb7dc4fc8ed67e597ea14c877c3b3f1cb2d7a42e
Status: Downloaded newer image for bufbuild/buf:latest
could not clone file:///workspace/.git: exit status 128
Cloning into ''...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
```

**Shell script, that's executed, looks like**
```
#!/usr/bin/env bash

docker run --volume "$(pwd):/workspace"  --workdir /workspace   bufbuild/buf check breaking --against '.git#branch=master'
```

**Comment by johanbrandhorst** [comment]
A few question marks here:
* Is $(pwd) a git repository?
* Does the git repository in $(pwd) have a master branch to compare against?
You may need to run `git fetch` to tell bitbucket to perform a deeper clone of your repository, so that the master branch is available locally. This is necessary in github actions, for example. See https://github.com/bufbuild/buf-example/blob/master/Makefile#L7-L9 for more information.

This is likely an environmental issue, and it would be easier to help you via our [Slack workspace](https://join.slack.com/t/bufbuild/shared_invite/zt-f5k547ki-VDs_iC4TblNCu7ubhRD17w), so please reach out to us there if you need more assistance.

**Comment by bufdev** [comment]
@nitinbhojwani please let us know answers to the above - this is likely one of the above issues

**Comment by nitinbhojwani** [comment]
> Does the git repository in $(pwd) have a master branch to compare against?

I tried adding `git fetch` and `git fetch origin master` before the below command in sh script, but none helped.

```
docker run --volume "$(pwd):/workspace"  --workdir /workspace   bufbuild/buf check breaking --against '.git#branch=master'
```

**Comment by nitinbhojwani** [comment]
Trying below command as (mentioned in the docs), throws `invalid dir path: "http://bitbucket.org/<org_name>/<repo_name>"`

```
docker run --volume "$(pwd):/workspace"   --workdir /workspace   bufbuild/buf check breaking --against 'http://bitbucket.org/<org_name>/<repo_name>'
```

**Comment by bufdev** [comment]
That's not the correct path per the docs - you have to add `.git` to the end, ie `http://bitbucket.org/foo/bar.git`

**Comment by bufdev** [comment]
Your earlier error shows that `$(pwd)` is not a git directory that contains a master branch, ie the following will fail:

```
git checkout master
```

This is an issue with your local development environment
