### ISSUE TITLE
buf breaking against git fails when there are imports in other directories

### ISSUE THREAD

**Issue by aschmitz-crnc** [bufbuild/buf#1905]
Please find attached a minimal git repo with a `buf.yml` and two proto files, one importing the other. The files lint fine, but `buf breaking` fails. I think this is due to the fact that the proto files reside in a subdir `api/proto`. My guess would be that `buf breaking`  doesn't chdir into the subdirectory where I ran the command itself, and then can't find the import anymore. IMHO buf should always work from where `buf.yml` is located. Which is when `buf lint` also works fine.
The tarred git repo: [buf-breaking.tar.gz](https://github.com/bufbuild/buf/files/10941312/buf-breaking.tar.gz)
What I ran:
```
cd api/proto
buf lint # runs fine
buf breaking --against '../../.git#branch=master' # fails with this error:
# api/proto/test/v1/test.proto:5:8:other/v1/other.proto: does not exist
```

**Comment by aschmitz-crnc** [comment]
Oh... found out about #subdir just now... Sorry. :-D

**Comment by timostamm** [comment]
You want to compare two sub directories against each other. With `cd api/proto`, you have selected the sub directory for your input. You have to select the same sub directory for the _against_ input, so that you are actually comparing the same directories.

The [subdir option](https://docs.buf.build/reference/inputs#other-options) for the git path is the correct solution here. I'm going to close this, but thanks for raising the issue - this might help someone else having the same question, and it gives us something to think about for improving our docs.
