### ISSUE TITLE
Support format options for buf curl --data

### ISSUE THREAD

**Issue by joshcarp** [bufbuild/buf#1907]
The `buf convert --from` and `--to` flags both support specifying the format with `#format=[json|bin]` or file extensions. Supporting this for `buf curl` would also be nice and consistent with the behaviour of other buf flags:

```
 echo '{"name": "Alice", "age": 30}' | buf curl <url> --data=-#format=json
cat file.bin | buf curl <url> --data=-#format=bin
```

**Comment by doriable** [comment]
Closing this for now, since I don't think this quite works with `buf curl`, given that the output of `buf curl` is not necessarily restricted to the response body, it also has additional `curl` output information. So additional formatting doesn't really make sense, and the conversion of data should be restricted to `buf convert`.
