### ISSUE TITLE
Support origin/master as branch for break checking

### ISSUE THREAD

**Issue by odsod** [bufbuild/buf#21]
We've found that it's easier to support both local and CI break checking when we use the git source instead of the SSH source (the SSH source might be easier to use if it integrated with ssh-agent to not require providing the key passphrase).

When using the git source, we want to break check against origin/master.

We currently do it like this:

```make
.PHONY: buf-check-breaking
buf-check-breaking: $(buf)
	@git fetch origin master
	@git branch --no-track -f buf-break-check origin/master
	$(buf) check breaking --against-input '.git#branch=buf-break-check'
	@git branch -D buf-break-check
```

Would it make sense to say `.git#branch=origin/master` here?

Currently the result is:

```bash
 $ buf check breaking --against-input '.git#branch=origin/master'
could not clone .git: couldn't find remote ref "refs/heads/origin/master"
```

**Comment by bufdev** [comment]
Let us look into this. A couple quick notes:

- I think this may just be because this was written in a GitHub issue and this may be semi-obvious, but the above two commands are doing different things - in one case, you're checking if the changes on `master` are breaking relative to the `buf-break-check` base, in the `origin/master` case, assuming `git branch` = `buf-break-check`, you're checking if the changes on `buf-break-check` are breaking relative to `origin/master` (which is what I think you want).
- I think it's preferable to not have the Buf CLI tool to expose every feature of git - the goal here was to provide a few mechanisms to do comparisons, and in the long term, we expect the primary method will be the Buf Schema Registry, so something like `--against-input buf.build/foo/bar:v1.0.0`.
- Generally, the above is what we'd recommend if you want to do comparisons against your local checkout in CI, it's similar to what we do in https://github.com/bufbuild/buf-example/blob/master/.github/workflows/ci.yaml (which does a checkout of `master`, then does a checkout of the commit under test, then runs `buf check breaking --against-input .git#branch=master`).
- **With all that said**, we do want people to be able to check against remotes, so this is worth looking into (as well as integrating with `ssh-agent`), and we certainly want to add this feature if it's feasible.

Note that the implementation uses https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing#ReferenceName so this is what we'll be looking through. I believe this might mean using https://github.com/src-d/go-git/blob/v4.13.1/plumbing/reference.go#L72 and adding `.git#remote=origin/master` as a possibility, similar to how we added `#tag=`, but need to look into the implications.

Will update this issue as we have more data, will let you know. Thanks for filing this.

**Comment by bufdev** [comment]
@odsod - I don't think this is possible, after attempting to implement it.

The issue is that the `--against-input` clone logic is doing just that - making a fresh clone of your git repository from your local copy, pointing to either the branch or the tag you specify. The clone doesn't have the same remote that you have in your local copy, so `origin/master` doesn't mean the same thing. When I dumbly add the ability to do `#remote=origin/master` based on https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing#NewRemoteReferenceName it ends up erroring itself, which make sense:

```
could not clone .git: couldn't find remote ref "refs/heads/origin/master"
```

In the context of the new clone of your local copy, there is no remote ref `origin/master`.

This gets to a few issues:

1. The Git tooling inside Buf isn't meant to be a replica of complete git - for complicated operations, you should push to external `git` before calling `buf`. The tooling within `buf` is meant to be able to do local and remote clones of branches, and now tags, with basic support for authentication.
2. This isn't the first issue that's come up with Buf's Git tooling, see #14. Perhaps there's an argument to be made that github.com/src-d/go-git should not be used, and Buf should shell out to external `git` - this would take care of all authentication issues as well.
3. If we don't decide to do (2), perhaps we should add the ability to use `ssh-agent`, but this means there's likely another external dependency - `buf` is meant to be completely self-contained, as most of the logic will eventually be part of Buf's SaaS offerings as well.

I think this issue needs a bit more thought on our part as to what we want to do going forward, and before v1.0. Let me know if you have any thoughts.

**Comment by odsod** [comment]
I get your point. My 5 cents on the dependency issue for git and the ssh-agent is that the `go` toolchain (which I believe shells out to git and integrates with the ssh-agent) reduces the stigma a little bit on those particular dependencies. :smile_cat: 

I understand the advantages of being able to clone git repos entirely in-memory and not hit the disk with go-git too.

Since we have a workflow with the existing functionality that meets our needs (checking out a local branch from the origin branch before break checking) I wouldn't mind closing this issue.

**Comment by bufdev** [comment]
Yea I thought about it, and we might replace this issue entirely and just remove go-git, and shell out to git. You made a lot of good points there. We need to evaluate issues though (temp files for example).

**Comment by bufdev** [comment]
Replacing this issue with https://github.com/bufbuild/buf/issues/34
