### ISSUE TITLE
IntelliJ IDEA integration

### ISSUE THREAD

**Issue by listepo** [bufbuild/buf#227]
Any plans to support developers with IntelliJ IDEA?

**Comment by bufdev** [comment]
No particular plans, we could look into it in the future though

**Comment by AlexeiZenin** [comment]
+1 to this

**Comment by musufyian** [comment]
+1

**Comment by asahasrabuddhe** [comment]
What kind of integration are we talking about here? I would love to work on it

**Comment by dontstabai** [comment]
Big things that would be helpful from this:
1. Buf lint integration
2. Buf breaking integration
3. Option to auto-generate on save

**Comment by nordicdyno** [comment]
I will be happy to see a general solution for external tools for editing .proto files, they know nothing about buf dependencies (like googleapis), so .proto file becomes incorrect from their point of view, also go to the definition doesn't work either

**Comment by dontstabai** [comment]
@nordicdyno I agree with you that there are lots of ways to improve the experience, but you might have a slightly better time if you use [the HIGAN protobuf plugin](https://plugins.jetbrains.com/plugin/16422-protobuf) rather than the bundled one.

Also, both plugins allow you to specify additional folders where they should look for protos. If you point them at the a local copy of grpc/etc, you should be able to get rid of the import errors. It will still dumbly assume that they're included even if they're not, but it's better than it just showing errors all the time.

**Comment by amckinney** [comment]
A better story around IDE integration (including IntelliJ) is on our [roadmap](https://docs.buf.build/roadmap#better-ide-integration), but it's not our primary focus _right now_.

Like the roadmap describes, we're very interested in LSP since it would give us a solution for so many editors without needing to tailor a solution to each editor independently (like [vim-buf](https://github.com/bufbuild/vim-buf) and [vscode-buf](https://github.com/bufbuild/vscode-buf)).

I don't have much familiarity with IntelliJ, but it looks like [IntelliJ doesn't support LSP](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360001627960-IntelliJ-support-for-Language-Server-Protocol-as-a-client-).

We'll eventually develop a solution that will work for our IntelliJ users (regardless of LSP support), but we don't have a timeline for this just yet.

**Comment by leoluk** [comment]
One very simple workaround is to just add buf's cache directories as extra search paths:

![image](https://user-images.githubusercontent.com/859697/143273536-3ec5b7f7-157d-4c8f-a03b-306b90abb8a1.png)

**Comment by amckinney** [comment]
Thanks @leoluk, more docs on the module cache can be found [here](https://docs.buf.build/bsr/overview#module-cache). I should have also mentioned that you can set up `buf lint` to run on a save with a couple configurations described [here](https://docs.buf.build/editor-integration#jetbrains-ides).

**Comment by nordicdyno** [comment]
> One very simple workaround is to just add buf's cache directories as extra search paths:

I've thought about it. I think it would be handy if buf had some command which prints all cache paths for a lock file, so it would be easy just copy&paste them.

**Comment by nordicdyno** [comment]
So, I've solved my problem by just putting googleapi's files which are used as includes into `third-party` directory, which is not in `build/roots` list. I suppose that in a new `1.x` buf version I will be forced to use `excludes` option because `roots` have been removed.

**Comment by devkanro** [comment]
Hello folks, I am happy to inform you that the first version of Buf integration for JetBrains IDEs has been released ([community support](https://plugins.jetbrains.com/plugin/16422-protobuf)).

There are some highlight features for Buf:
1. Code completion and documentation for buf configuration files (only for v1).
2. Auto config protobuf import roots from buf.yaml and buf.work.yaml, it support locked deps and workspace local module.
3. Execute buf command like buf build , buf mod update and view the module deps tree in Buf Tool Window.
4. Code annotator by buf lint.

Explore more editing features of protobuf:
1. Smarter import management, auto import and import optimization.
2. Smarter import path management, auto config from libraries.
3. Protobuf decompile for golang.
4. Import fix suggestion.

Search and install protobuf in plugin page or download it from [JetBrains Marketplace](https://plugins.jetbrains.com/plugin/16422-protobuf/versions).

If you feel usable for this plugin, you can [comment and rating](https://plugins.jetbrains.com/plugin/16422-protobuf/reviews) it, share it to your workmate.
If you have trouble using this plugin, feel free to [create Github Issue](https://github.com/devkanro/intellij-protobuf-plugin/issues/new).

![image](https://user-images.githubusercontent.com/9367842/164955124-5ac20fc1-570e-44b7-8138-6be7495c029a.png)
![image](https://user-images.githubusercontent.com/9367842/164955128-5626818e-0e61-4e4d-8c92-de69315502c1.png)
![image](https://user-images.githubusercontent.com/9367842/164955137-2fbb74f5-29fe-4cec-a4ad-22b73906f42c.png)
![image](https://user-images.githubusercontent.com/9367842/164955142-a4f8404a-c240-4a2e-a6e9-3a7a0b3737dd.png)

**Comment by bufdev** [comment]
We're going to be releasing bufbuild/intellij-buf in the next week or so as well.

**Comment by amckinney** [comment]
This was released https://github.com/bufbuild/intellij-buf 🎉
