### ISSUE TITLE
Double underscores as violation of ENUM_VALUE_UPPER_SNAKE_CASE

### ISSUE THREAD

**Issue by augi** [bufbuild/buf#2365]
Hello, we have an enum called `FileType`, and `FILE_TYPE__P_MS` value is reported by the `ENUM_VALUE_UPPER_SNAKE_CASE`. Please note that `_P_MS` is the _core_ value for us, so the double underscores are expected there.

**Comment by bufdev** [comment]
Understandable - this is an exception to the rule, however, and generally we'd expect double underscore to be unintentional. The way to deal with this is to set up an ignore: https://buf.build/docs/lint/overview#ignore_only - this allows you to ignore this specific rule for the specific file with this definition. Let us know if you have any other questions.

**Comment by augi** [comment]
Yeah, we are currently using `// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE` comment as a hotfix, but as it is a part of generated code, it is not so easy to incorporate it long-term 😢 

Couldn't it be possible e.g. to relax the linting rule to check if there are more double-underscores?

**Comment by bufdev** [comment]
I think what we're saying is we don't want to relax the lint rule - in 99.999% of cases, `__` indicates something that a user would want to be reported as a lint error (likely due to a typo), not something that is actually intentional. For such cases, ignores are the solution to use.

I would recommend setting the ignore in the `buf.yaml`, not as a code comment, as this should more easily persist long-term.
