### ISSUE TITLE
docs: "copy" button includes $ prefix for shell command

### ISSUE THREAD

**Issue by howardjohn** [bufbuild/buf#238]
When clicking the "copy" button on a page like https://docs.buf.build/tour-1#clone-googleapis, we get the full

```
$ GOOGLEAPIS_COMMIT="d4aa417ed2bba89c2d216900282bddfdafef6128"
$ git clone https://github.com/googleapis/googleapis
$ cd googleapis
$ git reset --hard "${GOOGLEAPIS_COMMIT}"
```
copied. Also highlighting copies the `$`. This makes it hard to paste

Other docs I have seen make it so the `$` is not highlightable and/or the copy doesn't include the `$`, which makes the UX a bit better.

an example of copy not including `$`: https://istio.io/latest/docs/tasks/traffic-management/request-routing/#apply-a-virtual-service.

**Comment by bufdev** [comment]
Totally fair, we will update across the whole docs repository, thanks!

**Comment by bufdev** [comment]
Related: https://github.com/facebook/docusaurus/issues/1745

We deleted the `$`, but the result made example commands less clear, so we're in a tough spot on this one. If the above issue were fixed, we'd be in a better spot, we're pursuing a complete rewrite of docs.buf.build at the moment, so this will likely go away. Closing for now as we're not going to action on this directly, but this should be fixed in a future iteration.
