### ISSUE TITLE
Auto download module from Git repository

### ISSUE THREAD

**Issue by robinbraemer** [bufbuild/buf#262]
The current way of pushing a module to the registry is by using the client:
```
buf beta registry repository create buf.build/$BUF_USER/petapis
```

I suggest that we add support for automatic git repository lookup as Go does on-demand when a module version is not yet found in the module proxy storage so that proto developers don't need to set up this extra CI pipeline to publish new API versions.

**Comment by bufdev** [comment]
Thanks for the suggestion. This is a fundamentally different model from what we have built - we did consider this path, but decided against it. The real question here is decentralization vs centralization - do you pull your Modules from other sources of truth, or do you push your Modules to a central registry? Golang modules represent the former, while tools such as Docker (and Buf) represent the latter.

While decentralization is appealing, especially for brownfield systems, not having a central store of your Modules (and the Modules it depends on) has a lot of drawbacks in terms of the features you can build on top of the Module concept. There's no clear answer/you can argue either way, but on balance, we decided that centralization just has too many positives in terms of the features we can provide to customers from BSR.

At some point, we do plan to have automated builds, [similar to Docker](https://docs.docker.com/docker-hub/builds/), but this is not a priority, since setting up CI to push to BSR is very simple.
