### ISSUE TITLE
Number values are not varint

### ISSUE THREAD

**Issue by yaziciahmet** [bufbuild/buf#2922]
Hey guys, truly great job, made working with protobufs 100% easier! I encountered a possible problem.

When I test the following code:
```js
  const val = Int32Value.fromJson(1).toBinary();
  console.log("val", val.length, val);
```
It prints:
```
val 2 [8, 1]
```
But with varint encoding, 1 should be representable just with 1 byte. Is this a bug or am I missing something?

**Comment by yaziciahmet** [comment]
It seems that there is a scheme called tag length value, and 8 is there for that purpose. My bad guyz :). Keep up the great work!

**Comment by timostamm** [comment]
Hey Ahmet, you're right, the extra byte is the tag. Since you're already using JS/TS, here's what happens under the hood with @bufbuild/protobuf:

```ts
import { BinaryWriter } from "@bufbuild/protobuf";

const bytes = new BinaryWriter()
  .int32(1)
  .finish();
console.log(bytes); // Uint8Array(1) [ 1 ]
```

This encodes just the value `1` as signed, 32-bit varint, and it takes up just one byte.

But you're encoding the message `Int32Value`:

```proto
message Int32Value {
  // The int32 value.
  int32 value = 1;
}
```

When fields are encoded, they are prefixed with a tag, which combines the field number with the wire type of the field. We can encode the same message with the BinaryWriter:

```ts
import {BinaryWriter, WireType} from "@bufbuild/protobuf";

const bytes = new BinaryWriter()
  .tag(1, WireType.Varint)
  .int32(1)
  .finish();
console.log(bytes) // Uint8Array(2) [ 8, 1 ]
```

The wire type provides just enough information about the field so that it is possible to skip it - otherwise, Protobuf would not be able to handle new fields in a schema with old generated code.
