### ISSUE TITLE
Can I "clone" a BSR repo as "git clone" in a Git repo?

### ISSUE THREAD

**Issue by Jisu-Woniu** [bufbuild/buf#2998]
As mentioned in #1350, buf repositories are easy to push to, but hard to pull from. Is there a way to "clone" a repository with all its config files like buf.yaml, buf.lock and buf.gen.yaml, so I can work with colleagues in different Git repositories?

Some alternatives I came up with:

- Mark a Git repository as the "main" repository, and all changes are made from that repository, and pushed from there.

**Comment by nicksnyder** [comment]
Hey Jisu, the short answer is that you can't clone from the BSR as if it was a Git repo today. Can you share more details about what you are trying to do and why you would value being able to pull down all the files?

If you are just trying to generate code, then that is exactly what `buf.gen.yaml` is for, and it is intended that each client of your API can define their own `buf.gen.yaml`.

Alternatively, and even better, if you have clients that just want to use generated code for your module, they can use [Generated SDKs](https://buf.build/docs/bsr/generated-sdks/overview) instead of needing to generate code at all.

**Comment by bufdev** [comment]
You can also use `buf export` to export definitions from the BSR https://buf.build/docs/reference/cli/buf/export.

Closing as there's no action items here - let us know if you need more help!
