### ISSUE TITLE
buf export --exclude-imports not being applied

### ISSUE THREAD

**Issue by rgaskill** [bufbuild/buf#3002]
I am trying to upgrade from buf v1.25.0 to v1.32.0.  We are using the export command to download protos from a separate git repo.  After upgrading to the latest version of buf the export command now fails with the error:

```
xxxx/xxxx/xxx/xxx/xx/xxxx.proto:22:8:import "google/api/annotations.proto": file does not exist
```

I would expect the exclusion of the imports would prevent this check or is there a different way to prevent this check with the export command in v1.32.0?

**Comment by rgaskill** [comment]
Here is the command:

```
buf export ssh://git@github.com/xxx/xxx.git#branch=xxx \
	--exclude-imports \
	--path proto/xxx/xxx \
	--path proto/xxxr/xxx \
	--path proto/xxx/xxx \
	--path proto/xxx/xxx \
	--path proto/xxx/xxx \
	--path proto/xxx/xxx\
	--path proto/xxx/xxx \
        --path proto/xxx/xxx -o .
```

This command previously worked in v1.25.0

**Comment by doriable** [comment]
Thanks for sending this through, a similar issue has been identified and we'll be addressing this today! https://github.com/bufbuild/buf/issues/3000

**Comment by doriable** [comment]
So we've resolved some issues we were seeing with `--path` when working with git inputs (the linked issue), and I was testing the case you've provided and have been unable to get an exact repro on the imports error message. Is there any chance you could provide an example git repo that provides a repro? In the meantime, we are planning on releasing a version of the CLI to fix `--path`.

**Comment by rgaskill** [comment]
I will make a simple public repo and try to reproduce.

**Comment by doriable** [comment]
Thank you for this, this was been very helpful to debugging! Some information about this:
- this behaviour changed and has been present since `1.28.0` onwards, where we basically require the input to be in a buildable state in order to export the image (in the case of the repro, the git repository did not contain any resolved imports in a `buf.lock`, so that's the issue we are running into)
- that being said, we do think it's valid to `buf export` an input that does not build -- as you alluded to in the issue, `--exclude-imports` should by nature ignore the need for any imported files. So we are currently exploring a fix for `buf export` specifically, will update again soon

**Comment by rgaskill** [comment]
Thank you, I look forward to the update.

**Comment by doriable** [comment]
This has now been merged and will go out with the next release!

**Comment by rgaskill** [comment]
Awesome!  Thank you
