### ISSUE TITLE
Allow usage of out of repo proto files

### ISSUE THREAD

**Issue by sashayakovtseva** [bufbuild/buf#302]
Hello,

I wonder why buf doesn't allow specifying arbitrary include paths.

Consider this example: a dev team is having a set of microservices, each one in a different repo. All of them are using, let's say, googleapis proto files. Instead of vendoring same proto files in every repo, they agreed on installing them locally and/or in builder docker image that is used in CI/CD. 

With protoc/prototool it is possible to specify `/usr/local/include` (or any other) as a source of proto files. Lack of this option in buf doesn't make sense to me, so I'd like know what exactly made you restrict include paths and if there is any way to workaround the example above other than vendoring same proto files in each repo.

**Comment by johanbrandhorst** [comment]
Hi thanks for your issue!

We're currently hard at work on the Buf schema registry, which will allow you to depend on things like `googleapis` and your own internal protobuf definitions in a way that will feel familiar to how it works in other language ecosystems. You can read a bit more about it in our roadmap: https://docs.buf.build/roadmap#the-buf-schema-registry. It's currently available in a private beta which you can sign up for here: https://buf.build/waitlist.

Indeed, depending on `googleapis` is available today even for users who aren't part of the private beta, you can see instructions in the [grpc-gateway README](https://github.com/grpc-ecosystem/grpc-gateway#usage), and an example in the [grpc-gateway-boilerplate repo](https://github.com/johanbrandhorst/grpc-gateway-boilerplate).

Given that the schema registry is going to be available publicly _soon_, I'm sure you understand why we haven't implemented this functionality you're talking about, since it's fundamentally worse than a modern dependency management solution.

**Comment by sashayakovtseva** [comment]
Great! Thanks for the explanation, looking forward for the BSR release! 

Already found some packages I need there :)

Is there a way to lock a dependency on a particular version? E.g. `buf.build/beta/protoc-gen-validate` that is built for `v0.5.1` tag from https://github.com/envoyproxy/protoc-gen-validate?

**Comment by johanbrandhorst** [comment]
We recently introduced tags, but for now we're just tagging by Git commit SHA, so you won't be able to find that particular tag hosted on the BSR. You should be able to lock to  `6ca6c537664a5ca0d292ca98a0bb913d14a7876e` though, the latest commit for `protoc-gen-validate`. We'll expand these capabilities in the future, but for now that's all that's available.

**Comment by bufdev** [comment]
Closing as I think this is resolved.
