### ISSUE TITLE
breaking: --exclude-path not working as expected

### ISSUE THREAD

**Issue by tiagomota** [bufbuild/buf#3168]
### GitHub Repository

https://github.com/tiagomota/buf-breaking-issue

### Commands

```shell
1. Clone the repo into local machine
2. Run `cp -R buf-breaking-issue/ /tmp/buf-breaking-issue`
3. On the original cloned repo go to /proto/foo/foo.proto file and introduce a breaking change (ex.: Change address field from 2 to 3)
4. Run `buf breaking --against /tmp/buf-breaking-issue` and verify breaking change is correctly ignored as per what is configured in `buf.yaml`
5. Comment out the ignore block in buf.yaml > breaking block.
6. Run `buf breaking --against=/tmp/buf-breaking-issue --exclude-path=proto/foo/foo.proto`
```

### Output

```shell
Step 6. outputs something like this: Failure: ../../(...)/buf-breaking-issue/proto/foo/foo.proto: is outside the context directory
```

### Expected Output

No errors on step 6., just like when running step 4.

### Anything else?

Buf version: 1.34.0

**Comment by oliversun9** [comment]
Hi there, thanks for filing this! We will investigate and get back to you.

**Comment by doriable** [comment]
The path you have passed to the flag, `--exclude-path` is relative to the execution context of the command. So currently you have two modules:

- `/tmp/<module>`
- `/path/to/<module>`

Since you are running buf breaking in `/path/to/module`, when you pass `--exclude-path=proto/foo/foo.proto`, paths passed through CLI flags are considered relative to the execution context of your command. So the absolute path of the exclude in your example would be `/path/to/module/proto/foo/foo.proto`, and when this is applied to your `--against /tmp/module`, it is taken as relative to that.

When comparing two local modules, as you noted in your repro, we generally recommend using the `ignore` key in `buf.yaml` configuration, since this ensures that each config is applied correctly to their respective inputs.
