### ISSUE TITLE
Use server reflection as a valid input for proto files

### ISSUE THREAD

**Issue by ahmednfwela** [bufbuild/buf#3171]
### Feature

The [reflection protocol](https://grpc.io/docs/guides/reflection/) (defined [here](https://github.com/grpc/grpc-proto/blob/master/grpc/reflection/v1/reflection.proto)) can be used to retrieve all available services hosted on a grpc server.

using this rpc it's possible to invert the returned proto descriptors back into their original .proto file format ([grpcurl just did this recently](https://github.com/fullstorydev/grpcurl/pull/475)).

Thus making it possible to use as input in buf cli, mainly `buf generate`

**Comment by doriable** [comment]
Thanks for filing this issue! From our perspective, the descriptors returned from reflection does not contain information such as `SourceCodeInfo`, etc. and would be unstable to support it as a first class input in the `buf` CLI.

That being said, the Proto descriptors and subsequently the Protobuf definitions inferred/generated from `grpcurl` can be used as inputs already to `buf generate`, assuming you have a `buf.gen.yaml`:

```
$ grpcurl -plaintext -proto-out-dir "out_protos" "localhost:8787" describe my.custom.server.Service
$ buf generate out_protos
```

**Comment by ahmednfwela** [comment]
@doriable what i am suggesting is inlining what grpcurl does into buf cli, as this will greatly simplify developer experience by not having to maintain 2 binaries just to generate protos

if you are accepting contributions I can create a PR

**Comment by doriable** [comment]
I have understood the original request and apologies, I should've elaborated more in my previous response. The [`inputs` key in `buf.gen.yaml`](https://buf.build/docs/configuration/v2/buf-gen-yaml#inputs) maps directly to all the [input types](https://buf.build/docs/reference/inputs) supported across the `buf`. So in order to support this feature request, we would either need to break this mental model, which is not a product/design decision we are able to make at this time, or we would need to add support for it as an input as a whole. And as mentioned, after discussing this issue with the team internally, we came to the conclusion that the descriptors from the server reflection Protocol is not viable to support as a first-class input type.

That being said, we can explore supporting similar features for interacting with the reflection protocol through `buf curl` to output descriptors, which would help reduce the maintenance overhead for binaries.
