### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by dpservis** [bufbuild/buf#3174]
### What's up?

Hi,

it is not obvious to me how I can build on Windows with native tools (not WSL). The makefile dows not work as it is looking for the OS versio nand I wonder how you build your Windows executables. Any guidance will be appreciated!

Kind regards,

Dimitris

**Comment by doriable** [comment]
When building `buf` from source on Windows machines, I use the [Go](https://go.dev/dl/) toolchain directly in Powershell:

```
go build ./cmd/buf
```
This compiles a Windows executable that can then be run. If you want to install it, you can run `go install`. Docs on the Go toolchain are available [here](https://go.dev/doc/tutorial/compile-install).

If you are doing this, I would recommend checking out a specific [tag/version](https://github.com/bufbuild/buf/tags) so that your executable is versioned the same way as our releases.

**Comment by dpservis** [comment]
Thanks - worked perfectly, maybe you could add this tip in the documentation?

**Comment by doriable** [comment]
Yep, added docs/instructions to the "Source" tab on our installation page! :) https://buf.build/docs/installation
