### ISSUE TITLE
Unreleased google.golang.org/protobuf version now in use

### ISSUE THREAD

**Issue by NathanBaulch** [bufbuild/buf#3321]
### What's up?

Starting in buf v1.40 my generated .pb.go file headers changed from:
```
// 	protoc-gen-go v1.34.2
```
to
```
// 	protoc-gen-go v1.34.2-devel
```
It looks like commit #3279 upgraded `google.golang.org/protobuf` to the unreleased development version `v1.34.3-0.20240816073751-94ecbc261689`. Was this intentional?

**Comment by bufdev** [comment]
You'll have to provide us a reproducible example. Buf's dependencies have no impact on your generated code, that is solely dependent on the version of protoc-gen-go you install.

**Comment by NathanBaulch** [comment]
Why are you closing my issue before I've had an opportunity to provide a reproducible example?

**Comment by bufdev** [comment]
The issue instructions were not followed - we specifically call out this scenario:

> If this is a question about some behavior you are witnessing, and you do not provide a minimal reproducible example in a GitHub repository, we may have to close your issue. We apologize, but we have to be efficient with our support requests, and we appreciate your help.

Please do not file issues without reproducible examples - it hurts our engineering team's ability to respond to support requests.

**Comment by bufdev** [comment]
Further commentary here:

My bet is you are installing from source and using the blank import method i.e. `import _ "github.com/bufbuild/buf/cmd/buf"` to make this appear in your `go.mod`. Additionally, you are installing `protoc-gen-go` using a similar method. As such, since `buf` has a dependency on an unreleased `google.golang.org/protobuf` version, your `go.mod` gets updated to this version, which changes the installed version of `protoc-gen-go`.

This is a perfect example of why the blank import method of tool dependencies is an anti-pattern - tools have independent lists of dependency versions, and by doing the blank import method, you are intermixing all of their dependencies. We don't support this installation method - you should install from the binaries, or at the least you should do `go install github.com/bufbuild/buf/cmd/buf@latest` as an independent installation command. We depend on an unreleased bug fix in `google.golang.org/protobuf`, and this was intentional. Using the blank import method causes these downstream issues when installing CLI tools, and this is a great example of why this method should never be used.

If I'm completely off-base and this isn't what is happening, I apologize and look forward to the reproducible example, however I can't see another way this could be realistically happening.

**Comment by NathanBaulch** [comment]
You're right - the project I inherited uses exactly this pattern, probably because it's a convenient way to centrally manage Go tooling versions from go.mod for quicker onboarding, etc.
For now I'll hold off on updating Buf until the upstream fix is merged and everything is kosher again.
Thanks for the in depth follow-up - perhaps others will benefit from this information in future.

**Comment by bufdev** [comment]
For what it worth: Buf (and other CLI tools) are free to depend on whatever versions of dependencies they like, whether beta, unreleased, or otherwise. Buf provides a stability guarantee for the CLI, not the code (and dependencies) within the CLI that are not publicly exposed. Therefore this situation is likely to arise again (with Buf, and with other CLI tools) - I'd highly recommend abandoning the blank import method of CLI tool installation.

**Comment by NathanBaulch** [comment]
This issue is probably going to be even more relevant in future with the `tool` go.mod directive proposed in Go 1.24.
https://go.googlesource.com/proposal/+/54d6775ff71ccbc00c276db2a4e4841d67011cf4/design/48429-go-tool-modules.md
