### ISSUE TITLE
buf lint PACKAGE_DIRECTORY_MATCH support prefix

### ISSUE THREAD

**Issue by manXcoder** [bufbuild/buf#3554]
### Feature

In the past, we managed proto files like: 
     aaa/aaa.proto       // package name is : com.xxx.aaa

Now, with buf, we need to organize proto files like this: 
     com/xxx/aaa/aaa.proto

This change is required to comply with the PACKAGE_DIRECTORY_MATCH rule.

While this structure may be helpful for sharing proto files across multiple projects, it results in overly deep directory hierarchies,  we need to make quite a few adjustments, especially when the protocol has already been shared with others..

If the PACKAGE_DIRECTORY_MATCH rule supported prefix matching, it would make it much easier to adapt to the buf style.

**Comment by bufdev** [comment]
Thanks for the issue. I understand your point of view on this one, but we feel pretty strongly that we need to keep the rule as-is, with no exceptions. Having your Protobuf packages map to your directory paths is almost a requirement for true cross-language modern Protobuf development - as you touch more and more language plugins, and the volume of Protobuf APIs increases, not being able to maintain this property becomes increasingly problematic. Adding the ability to have exceptions to this rule can have tough consequences for the community. Our recommendation would be to either:

(1) Move your Protobu files around to have the expected directory structure, or
(2) Ignore this rule entirely, or
(3) Write a [custom lint plugin](https://buf.build/blog/buf-custom-lint-breaking-change-plugins) that does the relaxed enforcement you desire. Writing a custom plugin allows you to enforce what you want, without us adding options to the mainline `buf` CLI tool that we think are hurting the community as a whole.

Going to close out this issue otherwise, but thanks for your continued support.
