### ISSUE TITLE
ENUM_VALUE_PREFIX should use (or have an option to use) the NestedName and not the Name

### ISSUE THREAD

**Issue by yinzara** [bufbuild/buf#356]
Currently when enabling the ENUM_VALUE_PREFIX lint rule and specifying an enum that's nested inside a message like this:
```protobuf
message MyMessage {
  enum MyEnum {
     MY_MESSAGE_MY_ENUM_INVALID = 0;
     MY_MESSAGE_MY_ENUM_VALUE_1 = 1;
  }
}
```

I get the error that `MY_MESSAGE_MY_ENUM_VALUE_1` (and _INVALID) should be prefixed with "MY_ENUM".

In Prototool linting, the enum prefix rule used the nested name and not the simple name.

This makes it so I can't configure Buf linting in the same way that Prototool used to lint.

There are two options to this:
1. change the rule to use the NestedName() of the Enum instead of the Name()
2. add a new "enum_value_prefix_nested_name" boolean option to the lint configuration that allows you to specify that this is the lint behavior desired

I'm happy to submit a PR for either.

Thoughts?

**Comment by bufdev** [comment]
https://docs.buf.build/migration-prototool#uber1-uber2

This was something that was done in `uber1` that was a mistake effectively, so `uber2` changed it. Buf didn't have backwards compatibility requirements with Prototool, as Buf is an independent tool that isn't related to Prototool, so it doesn't repeat that mistake.

As opposed to enabling linting that we don't think is what people should do, it would be better to ignore any values you have that use the old `uber1` way, either via `lint.ignore_only` or via a comment ignore.

**Comment by bufdev** [comment]
For more context: https://github.com/uber/prototool/tree/dev/style#nested-enums

In short, the naming style such as `MY_MESSAGE_MY_ENUM_VALUE_1` was dropped about 2.5 years ago with Prototool, it just happened to work due to backwards compatibility requirements. Buf, however, doesn't have these requirements with Prototool, and we think it's better to enforce this version going forward. Adding another option is a possibility, but on balance, this is configuration bloat for something we don't want users doing anyways, especially when they can just set an ignore.

**Comment by yinzara** [comment]
While I understand that Buf doesn't necessarily have compatibility with Prototool, the naming convention of including the 
nested message names is still a reasonable decision in the naming of enums.  If Buf is intended to be a tool that allows you to choose how you want to lint, then it should at least provide a config option to change the behavior to support both.

**Comment by bufdev** [comment]
Buf isn't intended to be a tool to give you unlimited choice in linting - the opposite, really. The goal is to have one way to do things, so that the community stays consistent, which providing this option would be contradictory to.

The whole goal of `ENUM_VALUE_PREFIX` is to make sure that C++ scoping rules aren't violated when users add new enum values to an enum in a given package. If it weren't for this language requirement, this lint rule wouldn't be necessary. Since an enclosing message provides such scoping, having users conform to a longer prefix is counterproductive, and isn't a feature we'd want available.
