### ISSUE TITLE
Not including deps in output from generated code in javascript/typescript

### ISSUE THREAD

**Issue by ralucas** [bufbuild/buf#378]
When using `deps`, particularly in the case of grpc gateway, i.e.
```
deps:
  - buf.build/beta/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
```

and building for typescript and javascript, it adds unnecessary imports and requires for unused modules and also doesn't add those dependencies to the output directory, i.e.

```js
var google_api_annotations_pb = require('../../../google/api/annotations_pb.js');
var protoc$gen$openapiv2_options_annotations_pb = require('../../../protoc-gen-openapiv2/options/annotations_pb.js');
```

```ts
import * as protoc_gen_openapiv2_options_annotations_pb from "../../../protoc-gen-openapiv2/options/annotations_pb";
```
So, it doesn't add these files into the output directory.  I would expect a `protoc-gen-openapiv2` directory in the output directory, but there is none.  Can this even be done with buf or is it another required generation step?

**Comment by johanbrandhorst** [comment]
The output files you are seeing are produced by the JS/TS plugins you're using, not `buf`, which only invokes the plugins. That said, `buf` decides what files it should ask the plugins to generate. It does not recursively generate the entire tree for a module, this is something we've recently discussed adding an option for, but we haven't done it yet because it doesn't make sense in all languanges (Go being one of them). In your case I believe you should be able to fix the issues by explicitly generating the two dependency modules into the same output directory, e.g.

```shell
$ buf generate buf.build/beta/googleapis
$ buf generate buf.build/grpc-ecosystem/grpc-gateway
```

Both of these will probably produce a lot of files that you don't need, unfortunately there's no way to automatically prune it to only the files you need today. Let me know if that fixes your issue, or if you want more direct support please feel free to join our [public Slack](https://join.slack.com/t/bufbuild/shared_invite/zt-f5k547ki-VDs_iC4TblNCu7ubhRD17w).

**Comment by ralucas** [comment]
Thank you.
