### ISSUE TITLE
Go Library Support

### ISSUE THREAD

**Issue by emcfarlane** [bufbuild/buf#390]
This is a general question on buf.build to use as a Go library. From a brief overview it looks like all the code is hosted under an internal package. Is there support or a plan to support building protoc descriptors from a go program? Thanks

**Comment by bufdev** [comment]
I believe your question is "are there plans to expose the Golang code within github.com/bufbuild/buf so that it can be used as a library elsewhere?" There are no plans to do so - the code within this repository it used to implement the `buf` CLI, and exposing it as a library means we will have a responsibility to not break CLI's internal implementation. We break the internal implementation all the time as we are developing the CLI, and havinga requirement to not do so would be burdensome.

**Comment by bufdev** [comment]
Closing unless there are further concerns - feel free to comment!

**Comment by emcfarlane** [comment]
Thanks I understand making it a library would add more work. Would be really nice though 😄.  I'm looking for a small API for compiling proto descriptors on top of the new filesystem apis. At the moment shelling out to `protoc` or `buf` also add a burden on using an alternative filesystem. Not wanting to reopen just wanted to highlight a use case. Thanks for the quick response!
