### ISSUE TITLE
Document how to consume an image for stub generation

### ISSUE THREAD

**Issue by joshdk** [bufbuild/buf#4]
This project is looking great so far! Anything that can improve tooling in this area is sure to be beneficial.

Reading through the documentation, it is not immediately obvious what I should **do** with an image, outside of linting.

With respect to stub generation, it sounds like you folks plan to provide this as part of the registry service (woah!), but in the meantime it would be great to have some docs that detail **how** to use an image in this way.

Experimenting in a simple Go repo, I was able to generate stubs by running the following:

```
$ buf image build -o image.bin
$ protoc \
    --descriptor_set_in=image.bin \
    --go_out=plugins=grpc:. \
    $(buf ls-files | grep -v vendor)
```

Is this the intended/optimal way? It would be **great** to be able to integrate `buf` into a stub-generation pipeline in this capacity.

Cheers!

**Comment by bufdev** [comment]
Will respond further tomorrow as it’s late for me, but two things in short:

- We haven’t overly documented this pattern because we’re concentrating on offloading stub generation.
- This is slightly documented at https://buf.build/docs/build-compiler though (including roughly the command you derived above heh).

Will respond fully tomorrow with additional details and help - thanks for the full detail though! You definitely have gotten into it and we appreciate that :-)

**Comment by bufdev** [comment]
One more quick note: protoc-gen-go specifically will complain with the above if you compile Protobuf files in different packages (at least last time I checked). See https://buf.build/docs/migration-prototool#prototool-generate for a temporary/hacky find and xargs-based solution to that :-)

**Comment by bufdev** [comment]
Hey,

Sorry for the delay in getting back to you here.

SO, here's the short and long of it:

Right now, you've accurately identified that there's not too much that you can do with Images with Buf :-) The main use case right now is breaking change detection - Images can be used to store the state of your Protobuf schema if you want to store this state manually, as opposed to comparing against the head of a git branch, or against a tarball. This matches up with what [protolock](https://github.com/nilslice/protolock) does with it's `proto.lock` file paradigm. For our testing, we use local and remote git branches, and have an example of this at https://github.com/bufbuild/buf-example, but not everyone will want to do that.

Images also allow you to have disparate Protobuf definitions in different repos, and then have a common store, and do breaking change detection against that store. The implementation of this is a bit of an exercise to the reader, but given that you have a common store of your Protobuf files, you can compare against a built image of these files for just your local files using the `--limit-to-input-files` flag on `buf check breaking`.

ANYWAYS, the real goal of Images is for use in our Buf Image Registry. This is what we're actively working on right now, but this doesn't exist yet and none of this code is public. Our fundamental assertion is that Protobuf stub generation is broken - every company figures out their own way to generate stubs, and eventually does one of two things:

1. Bazel, and then does a rough copy of external definitions to some GitHub repository, which is very error-prone
2. Some combination of Makefiles/scripts/Docker images that do "consistent" generation for a given version of your plugins

We want to change this model, and instead treat your API definitions as an asset you consume. We'll provide the ability to consume them in both Bazel and non-Bazel environments in a manner thats benefical to everyone. Even in Bazel environements, if you have ANY usage of Protobuf outside of a single Bazel repo - for example, any external definitions, or even multiple Bazel repos for different languages - having a common store is important.

That doesn't leave a very good world for now though. We could pretty trivially implement `buf generate` that calls protoc plugins for you, but we don't want to because we think this model is broken, and we're concentrated on moving to the Buf Image Registry. However, you can use Buf-created images in the ways we identified above. We don't recommend this for most users, but honestly if you were to incorporate this into your build pipeline and provide feedback, this would be hugely helpful, as it would hit the internal compiler even harder. If you do end up doing this, let us know, and then we'll give you discount code JOSHDK to use at checkout for 10% off any paid Buf services for a year :-)

**Comment by bufdev** [comment]
@joshdk does that answer the primary question about documentation for stub generation? The tldr being we don't really want to document it, on purpose, because we think the model is broken and we're moving on to something else. BUT, if you do use it as shown above, we'd be forever grateful as it will help us with compiler feedback.

**Comment by joshdk** [comment]
@bufdev Thank you for your in-depth response, it's great to read your perspective!

Nothing planned immediately, but I'll look into replacing some `make`+`protoc -I... -I... -I...` hackery with `buf`, and see if it simplifies/speeds things up. If I do, I'll definitely let you folks know. I also really appreciate your consideration and customer service, thank you!

---

Quick follow ups:
1. > This is slightly documented at https://buf.build/docs/build-compiler

Oops! I totally missed this during my initial read. FWIW, searching the docs site for `stub` or `descriptor_set_in` doesn't return this page.

2. > Protobuf stub generation is broken

Agreed; How do _you folks_ think it's broken, and how to fix it? 😁 

3. Does `buf` do anything _automagical_ with respect to Go modules and finding proto imports?

Cheers!

**Comment by bufdev** [comment]
1. Hmmm that's annoying, hopefully they will re-index soon (it uses https://community.algolia.com/docsearch)
2. Working on it, hopefully will put more in the roadmap soon :-)
3. No it does not - buf is language-agnostic right now, and there's nothing concerning external imports, i.e. you can't import cross-repo. This is a feature we might eventually get to, but this would be way after the Buf Image Registry is introduced. People have tried to solve this, but it's way trickier than it first appears, and it's our thinking that it first needs a reliable image registry to work. We recommend having all Protobuf definitions in a single repository.

I'm going to close this for now assuming the question is answered, but feel free to follow up!

**Comment by joeblew99** [comment]
Just wanted to chime in...

The ratio Al for big is true to me.

Now I want to see a theoretical example of a flow and with the how and why.
