### ISSUE TITLE
Inconsistencies between buf and protoc

### ISSUE THREAD

**Issue by WillAbides** [bufbuild/buf#417]
These are some inconsistencies between buf and protoc found in #411

### Form Feeds and Vertical Tabs

Protobufs containing the characters "\f" and "\v" fail with `buf generate` but succeeds with protoc. Buf outputs the message "syntax error: unexpected $unk". This seems to be coming from [this line](https://github.com/jhump/protoreflect/blob/fb56a945d0735c55f3bb1853ad1f99766ac126e7/desc/protoparse/proto.y.go#L925) in "github.com/jhump/protoreflect". I'm not familiar with goyacc, so my diagnosis stops there.

### Duplicate message and rpc names

Buf allows an rpc's name to be the same as a message's name in the same protobuf, but protoc does not.

For example:

```protobuf
syntax="proto3";

package a;

option go_package = "foo.bar/foo";

message Foo{}
message Bar{}

service MyService{
  rpc Foo(Foo) returns (Bar);
}
```

Buf generates code for ☝️, but protoc errors with the message: `"Foo" is not a message type.`

### Space after first number in extensions

With this protobuf:

```protobuf
syntax="proto2";

package a;

option go_package = "foo.bar/foo";

message Test{
  extensions 10to max;
}
```

protoc fails with `Need space between number and identifier.` but Buf generates code.

**Comment by bufdev** [comment]
Note I think the `rpc Foo(Foo) returns (Bar)` might be considered a `protoc` bug if anything.

**Comment by jhump** [comment]
> Note I think that protoc not compiling for rpc Foo(Foo) returns (Bar) might be considered a protoc bug if anything.

Yeah, it's a little inconsistent: in some places in the protoc code, their symbol resolution knows it's looking for a type or an aggregate element, so it can basically ignore name matches that could not be valid (like looking for a message and finding a method). Specifically: services _cannot_ define any elements other than methods, so it's strange that unqualified type references therein use the service scope (and thus can resolve to the name of a metod) instead of the scope of the enclosing file... 

For example, `protoc` is happy with the following source, even though the unqualified `Bar` (for the type of field `bar`) technically should resolve to the extension, not the message:
```
syntax = "proto3";

import "google/protobuf/descriptor.proto";

message Bar {
}

message Foo {
  extend google.protobuf.MessageOptions {
    string Bar = 10000;
  }
  Bar bar = 1;
}
```

**Comment by jhump** [comment]
The bit about the space between the number and next identify is kind of funny in just how explicit their lexer is with this error:
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/io/tokenizer.cc#L468
(Apparently `require_space_after_number_ ` is only false when this same lexer is used for parsing the protobuf text format.)

Luckily, that will make it fairly easy to reproduce in protoparse.

**Comment by bufdev** [comment]
Fixed in https://github.com/bufbuild/buf/pull/430
