### ISSUE TITLE
Module cache misses for identical references

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#482]
```
buf generate buf.build/bufbuild/buf --template enterprise/data/template/buf.go-server.gen.yaml
buf generate buf.build/bufbuild/buf --template enterprise/data/template/buf.ts-enterprise.gen.yaml
buf generate enterprise/proto --template enterprise/data/template/buf.go-enterprise.gen.yaml
buf generate enterprise/proto --template enterprise/data/template/buf.go-internal-api.gen.yaml
buf: downloading buf.build/bufbuild/buf:9ab0c4681d664e608a2b9509eaae10a3
buf: downloading buf.build/bufbuild/buf:9ab0c4681d664e608a2b9509eaae10a3
buf: downloading buf.build/bufbuild/buf:e050ba116fa04f7d8d6f5c01e2a83b83
buf: downloading buf.build/bufbuild/buf:e050ba116fa04f7d8d6f5c01e2a83b83
```

The same `ModulePin` was resolved multiple times, so we should only expect to see a single `buf: downloading ...` line per `ModulePin`.

**Comment by amckinney** [comment]
Prior investigation in #456 revealed that this is because the "fetch and put" portion of the cacher can be executed simultaneously by concurrent `buf` processes. We should be able to reuse the same file lock if we expose unsynchronized methods from the [moduleCacher](https://github.com/bufbuild/buf/blob/d25fed60dd48b4490112aeee8b505d137bc8f6c8/private/bufpkg/bufmodule/bufmodulecache/module_reader.go#L30).
