### ISSUE TITLE
V1 Readiness

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#483]
* Review commands (potentially review some that are deprecated and/or unused).
* Consider `--include-imports` and `--exclude-imports` in all `buf` commands.
* Allow `--path` filter to account for imports
* Audit API as a whole and verify it's ready for release
* Release V1 versions of all GitHub Actions.
* Re-consider split between buf config and buf mod. They overlap a lot, and we might want to combine these into one, or clarify their respective rules. Note that moving commands around is relatively straightforward, so we can do this in a backwards-compatible way.
* Audit all commands to be properly using workspaces

Maybe outside the scope of this ticket, but seems close enough to mention. 

We should tag all the GitHub actions as `v1` 

>  ...you can recommend that your users specify a major version when using your action, and only direct them to a more specific version if they encounter issues.

From the [docs](https://docs.github.com/en/actions/creating-actions/about-actions#using-release-management-for-actions)

This is a nicer experience and with a stable `buf` v1 for the CLI we can guarantee a stable experience for those actions. Could we capture that as part of this ticket, open a separate issue, or ignore?

UPDATE: this will also reduce the amount of documentation we need to manage throughout minor/patch releases. We just meed to keep them backwards-compatible.

**Comment by amckinney** [comment]
> We should tag all the GitHub actions as v1

In their current state, the GitHub actions use commands and flags that were deprecated in `v1`.

* `buf-push-action` uses `buf push` ([link](https://github.com/bufbuild/buf-push-action/blob/040008e05aecab7de4f5237a341c16bba68eba42/src/run.ts#L91))
* `buf-lint-action` uses `buf --version` ([link](https://github.com/bufbuild/buf-lint-action/blob/cacc586765be84d485141c084b5bd034973a618d/src/run.ts#L72))
* `buf-breaking-action` uses `buf --version` ([link](https://github.com/bufbuild/buf-breaking-action/blob/320295321f9d91c000d401bede59b3b8b524ce0c/src/run.ts#L104))
* `buf-setup-action` uses `buf --version` ([link](https://github.com/bufbuild/buf-setup-action/blob/main/src/run.ts#L72))

For the `v1` release of these GitHub actions, we can update the actions so that they only support the new commands (i.e. `buf mod push` and `buf version`), but everyone pinned to the GitHub actions pre-v1.0 will break if they don't manually specify their `version` in `buf-setup-action` (the latest version of `buf` is [installed by default](https://github.com/bufbuild/buf-setup-action/pull/5)). We expect that _most_ users of this action don't specify a `version` since this is recommended by the action's [README.md](https://github.com/bufbuild/buf-setup-action/blob/main/README.md).

In short, no matter what we do to update the actions to support the latest changes (e.g. https://github.com/bufbuild/buf-push-action/pull/8), users will break because they will be pinned to an older version of the action that does not account for the changes made to the `buf` binary.

We have a couple options here:
1. Update and release the GitHub actions as `v1` so that they require at least version `buf` `v1`, and announce that everyone should upgrade. Some users will experience failures until they upgrade.
    * To prevent this from happening in the future, we can adapt the `buf-setup-action`'s [default value](https://github.com/bufbuild/buf-setup-action/blob/main/action.yml#L10) so that we never use `latest` and instead update the `default` value to the latest version every time we make a `buf` release (which means we release `buf-setup-action` every time we release `buf`).
2. Revert back to `buf push` and `buf --version` so that the old actions remain functional.
    * This is less than ideal since we actually want to change these commands/flags, and we don't know how many users this will actually affect in practice.

**Comment by bufdev** [comment]
I'm kind of leaning to (2) having slept on it - thoughts? @doriable too

**Comment by johanbrandhorst** [comment]
vscode-buf also uses `--version`: https://github.com/bufbuild/vscode-buf/blob/main/src/buf.ts#L48.

**Comment by bufdev** [comment]
Is this complete/should we close this?

**Comment by bufdev** [comment]
@amckinney we should reconsider this and figure out what we have left to do

**Comment by amckinney** [comment]
Nearly has all of the moving pieces are in place. @doriable what's the estimated timeline until we can start finalizing the details and cut `v1.0`?

**Comment by doriable** [comment]
So the things that we still have left are:

- Surface the `--tracks` flag for the `push` command in the CLI (and any other `tracks` related commands for feature completeness). The flag already there and setup for `push`, but we currently do not have it exposed because the functionality for tracks is not yet ready for public consumption. Since this is not a sub-command under `beta`, I wanted to be cognizant of exposing this before we are ready for users.
- Migrate the server-side to use `b3` digest. We are ready on the CLI side, and I've prepared comms for customers, but this server-side change will force customers off of CLI versions before `v1.0.0-rc*`. I will say, this can be delayed to after announcing a `v1` version of the CLI, since it requires no additional changes to the CLI, so it is not a strict blocker. @lucperkins and I have some docs detailing this.

**Comment by doriable** [comment]
[v1.0.0](https://github.com/bufbuild/buf/releases/tag/v1.0.0) is out, so going to close this :) All subsequent things are now `v1` and onwards!
