### ISSUE TITLE
Regression in v0.55.0: failed to map insertion points: file defined multiple times

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#560]
See https://github.com/srikrsna/protoc-gen-gotag/issues/26

```
git clone https://github.com/srikrsna/protoc-gen-gotag
cd ./protoc-gen-gotag
rm buf.gen.yaml
cat <<EOF > buf.gen.yaml
version: v1beta1
plugins:
  - name: go
    out: .
    opt: paths=source_relative
  - name: gotag
    out: .
    opt: paths=source_relative,xxx=graphql+"-" bson+"-"
EOF
go install google.golang.org/protobuf/cmd/protoc-gen-go
go install .
buf generate
```

Results in:

```
Failure: failed to map insertion points: file "tagger/tagger.pb.go" defined multiple times
```

This did not happen in v0.54.0.

**Comment by johanbrandhorst** [comment]
The error reported here and that reported in the issue linked is different:
```
[error] [gotag]: open tagger/tagger.pb.go: no such file or directory
```

I think there's a race condition here in the invocation of the go_tag plugin. I'm not sure how it was working before, but it'll either result in the error in this issue (the duplicate generated files), or in the error reported in the original issue (no such file or directory). The README of the plugin itself recommends running the generator _after_ the original generator, so it seems to be completely accidental and arguably unintentional that the old generation supported this pattern. I think it only worked because the old generation was serializing the execution of the plugins, even though each plugin was executed in parallel. The new generation executes plugins and directories in parallel, so dependencies like this are no longer possible.

I think the resolution in the issue is the right one, and that `buf` is handling this correctly. The user should run two `buf generate` invocations to mimic the two `protoc` invocations recommended by the README.

**Comment by srikrsna** [comment]
It is not a race condition. I've updated the repo to include two buf invocations. Basically, it edits the generated Go source code to add the struct tags. One way of fixing it would be to give a flag to run plugins sequentially in buf. But this is a rare use case I wouldn't do it just for this.

**Comment by amckinney** [comment]
I agree that we shouldn't add a flag to support sequential generation for this case. In general, plugins should _always_ assume that they should invoke within a single `protoc` and/or `buf` invocation. If a plugin needs to modify the content of another plugin's output, they really ought to use [insertion points](https://github.com/protocolbuffers/protobuf/blob/2501e9b856c411239e2ae32bcc75518dcf840418/src/google/protobuf/compiler/plugin.proto#L172) (that's what they are for).

Unfortunately, [protoc-gen-go](https://github.com/golang/protobuf/tree/master/protoc-gen-go) doesn't support insertion points, so the only option for `protoc-gen-gotag` is its current behavior that requires the generated code to exist on disk (thus requiring two separate invocations).

As for the `"defined multiple times"` error originally seen by the user, this should only happen if the same file is being written by multiple plugins in the same `buf generate` invocation. From the example above, this means `tagger/tagger.pb.go` was being written more than once, potentially because the user configured `protoc-gen-go` more than once in the same `buf.gen.yaml`. However, it doesn't look that was the case, so there might be some more investigation needed here. I'll follow-up with any more details that I find with respect to this last error.

**Comment by johanbrandhorst** [comment]
> It is not a race condition.

Apologies for the misunderstanding here, I don't mean that `protoc-gen-gotag` is doing anything wrong. It's a race condition in that `buf generate` will execute the plugins concurrently, and sometimes `protoc-gen-go` will have written the files by the time `protoc-gen-gotag` looks for them, and sometimes it won't. The correct fix is the run in separate `buf` invocations, as you explained in the issue 👍🏻.

**Comment by amckinney** [comment]
@srikrsna We followed up with some better error handling on the "defined multiple times" error. It doesn't look like there's anything else to do here, so closing this as-is. Thanks for reporting the issue!
