### ISSUE TITLE
Handle Protobuf 3.12 optional declaration

### ISSUE THREAD

**Issue by jef** [bufbuild/buf#60]
### Description

In [protobuf 3.12](https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0), `optional` was added back in. Buf should account for that and decide whether it's a breaking change or not.

### What is currently being seen

`field has label LABEL_OPTIONAL, but proto3 must omit labels other than 'repeated'`

**Comment by bufdev** [comment]
This depends on https://github.com/jhump/protoreflect/issues/311

When that is fixed, Buf will be able to upgrade and be automatically fixed in terms of the compiler. In terms of being a breaking change, this will be detected as a breaking change as declaring something as `optional` in Protobuf 3.12 results in a bunch changing under the hood, namely an implicit `oneof`, which will be detected as a breaking change.

**Comment by bufdev** [comment]
https://github.com/jhump/protoreflect/pull/327

**Comment by bufdev** [comment]
This is released in v0.16.0.
