### ISSUE TITLE
Buf breaking fails when Git LFS is enabled

### ISSUE THREAD

**Issue by devnajjar** [bufbuild/buf#695]
Executing `buf breaking --against .git#branch=master --path <path to proto>` will fail with the error: 
`Error downloading object: <XXX> Smudge error: Error downloading <XXX>`

While on the other hand if I try to run it against some remote branch like: 
`buf breaking --against <LinkToRepo>.git#branch=master --path <path to proto>` it will work without any errors. 

Could this be related to issue mentioned in: https://github.com/bufbuild/buf/issues/424 ?

Thanks!

**Comment by cyinma** [comment]
Thanks for the report @devnajjar , we'll take a look into it 🙏

**Comment by robbertvanginkel** [comment]
@devnajjar what buf version are you using? Could you also provide some more details about the error message you're seeing? Git LFS should add more context on why it its failing but this is omitted by the last `<XXX>` in your report.

**Comment by robbertvanginkel** [comment]
Thanks that is helpful. I think this has something to do with how git lfs infers the lfs remote from the repo remote. I'll investigate more and work on a fix.

**Comment by robbertvanginkel** [comment]
I am able to reproduce it locally and I think I narrowed it down to how lfs handles local remotes. Finding the root cause was a bit trickier as it seems like later versions (v2.9.0 and onward) of `git-lfs` handle `file` remotes differently and I was seeing different errors at first for the same problem (unfortunately a newer git lfs doesn't solve this and fixing this will still require a buf update).

Now that I know where it is I'll be working on a fix!

**Comment by robbertvanginkel** [comment]
I think this may actually be fixed with a later version of lfs: the release notes for v2.9.0 (https://github.com/git-lfs/git-lfs/releases/tag/v2.9.0) mention "adds support for file URLs".

With my reproduction case, it seems like I get the same issue on older versions of lfs:
```
$ buf --version
1.0.0-rc8
$ git lfs --version
git-lfs/2.8.0 (GitHub; darwin amd64; go 1.12.7; git 30af66bb)
$ buf breaking --against '.git#branch=main,recurse_submodules=true'
Failure: could not clone file:///Users/robbert/lfstest/.git: exit status 128
Downloading file.proto (67 B)
Error downloading object: file.proto (34ecb9e): Smudge error: Error downloading file.proto (34ecb9e8ab62b5413d556a47f2a5c49d94a23ba49da6d4feccbb7bdf2b6ec92b): batch request: ssh: Could not resolve hostname file: nodename nor servname provided, or not known: exit status 255

Errors logged to /private/var/folders/vt/_gj7d6bx5ddbmdkhw48dhq1h0000gn/T/f61b523a-7026-45f5-ad28-b8f8de9a9242151874771/lfs/logs/20211118T153818.894577.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: file.proto: smudge filter lfs failed
```
Whereas with a newer version of git lfs:
```
$ git lfs --version
git-lfs/3.0.2 (GitHub; darwin arm64; go 1.17.2)
$ buf breaking --against '.git#branch=main,recurse_submodules=true'
$ echo $?
0
```

Could you let me know if updating lfs resolves this issue for you?

**Comment by devnajjar** [comment]
@robbertvanginkel Thanks a lot! 🙏 
It seems like updating git lfs has solved the issue! :)
