### ISSUE TITLE
Buf plugins

### ISSUE THREAD

**Issue by careless6666** [bufbuild/buf#707]
Hi. Are there any examples of buff plugins? I'm trying to write my own plugin (for generating grps methods and services for the dotnet), but I get an error with a code and a suggestion to contact support.
`buf generate
Failure: internal error, contact support, reference code: 751f80
`

Where can I find support if there is one?

If there is a ready-made plugin for dotnet then please advise

**Comment by amckinney** [comment]
We recently published the plugins built-in to `protoc` under https://buf.build/protocolbuffers/plugins, and nearly all of the gRPC plugins under https://buf.build/grpc/plugins.

In our investigation, we found that `grpc-dotnet` binary is actually the same as the `grpc-csharp` plugin, so we've only published https://buf.build/grpc/plugins/csharp for now. You should be able to use something like the following in your `buf.gen.yaml`:

```yaml
version: v1
plugins:
  - remote: buf.build/grpc/plugins/csharp:v1.41.1-1
    out: gen/proto/csharp
```

> Including the `v1.41.1-1` version is a best-practice so that you make sure to always execute the same plugin until you decide to upgrade. Omitting it will use the latest version of the plugin.

We realize that the `grpc-dotnet` plugin might not be as easily discoverable though, so we might consider publishing the same plugin under the https://buf.build/grpc/plugins/dotnet name in the future.

--

For future reference, the internal error we're seeing from your plugin is the following:

```
"failed to unmarshal generator response: proto: cannot parse invalid wire-format data"
```

Regardless, you should be able to use `buf.build/grpc/plugins/csharp` for your use case. Please let us know otherwise!

**Comment by careless6666** [comment]
Thank you very much!
