### ISSUE TITLE
[1.0.0-rc9] does not match stored digest

### ISSUE THREAD

**Issue by GaoJianAllen** [bufbuild/buf#790]
I update the buf to 1.0.0-rc9 and meet warning as below:
**_Module "buf.build/googleapis/googleapis:5860854adf6a48c39b19d54342b68385" has invalid cache state: calculated digest "b3-xi5p-ipG4lG8iOzD7LBmNPs015OkSjXFmgTuGfQ4URQ=" does not match stored digest "b2-WayFxGJKhSLbpMCQ-VZ5-3R5Gj9iRFYsMG7o57lgqog=". The cache will attempt to self-correct._**

The rc9 version can work well but the wierd warning.

**Comment by doriable** [comment]
Hi @GaoJianAllen, thanks for filing the issue. In `v1.0.0-rc9`, we are expecting a cache invalidation since we changed the digest that we are using for the cache ([release notes](https://github.com/bufbuild/buf/releases/tag/v1.0.0-rc9)).

> Users on v0.44.0 or after will have their module cache invalidated, but it will repair itself automatically.

This will result in the warning that you see above. Just for reference, this seems to be happening when you run `buf mod update`, is that correct? Once the cache has self-corrected, you should not continue to see the warnings.

**Comment by doriable** [comment]
It looks like this is happening with remote targets during the generation process, I was able to reproduce locally. Looking into this now!

**Comment by doriable** [comment]
The fix has been merged and a release as made https://github.com/bufbuild/buf/releases/tag/v1.0.0-rc10.
