### ISSUE TITLE
Comment in generated Go code shows unknown protoc version

### ISSUE THREAD

**Issue by lovromazgon** [bufbuild/buf#799]
After upgrading to `v1.0.0-rc9` I noticed that the comment in files generated with `protoc-gen-go` shows an unknown version of protoc. The same behavior persists in `v1.0.0-rc10`.

Here is how it looks like with `v1.0.0-rc8`:
```
$ go install github.com/bufbuild/buf/cmd/buf@v1.0.0-rc8
$ buf --version
1.0.0-rc8
$ buf generate
$ head -n 5 proto/api/v1/api.pb.go
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//      protoc-gen-go v1.27.1
//      protoc        v3.19.1
// source: api/v1/api.proto
```

And with `v1.0.0-rc9`:
```
$ go install github.com/bufbuild/buf/cmd/buf@v1.0.0-rc9
$ buf --version
1.0.0-rc9
$ buf generate
$ head -n 5 proto/api/v1/api.pb.go
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//      protoc-gen-go v1.27.1
//      protoc        (unknown)
// source: api/v1/api.proto
```

**Comment by amckinney** [comment]
This is expected behavior, but it wasn't included in the `CHANGELOG.md`. I'll update it to include a concise description of the following:

---

The `v3.19.1` version you saw was actually the version of `protoc` that we used to verify compatibility with `buf` - it wasn't actually the version of `protoc` used to generate your Go code.

This caused a lot of frustration in the community - they'd notice a diff in their generated code even when nothing changed at all. Unfortunately, this is actually in [plugin implementation](https://github.com/grpc/grpc-go/blob/51835dc0912b7a0b894bc0fdbfce167aea88f4cb/cmd/protoc-gen-go-grpc/grpc.go#L47) itself. This behavior is more confusing than it's worth - `protoc` wasn't used to generate this code at all, so it doesn't make sense to falsely claim that it was. 

For now, we've decided to assign a static value to the [compiler_version](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/plugin.proto#L94) parameter so that users won't notice a meaningless diff in their generated code and they won't mistakenly think `protoc` was used at all.
