### ISSUE TITLE
Breaking changes detector issues with git on windows

### ISSUE THREAD

**Issue by qblook** [bufbuild/buf#804]
Hello, here is a problem using buf for large repository:

```
buf.exe  breaking --path Proto\V1 --against .git#branch=develop
Failure: could not clone file://C:\code\.git: exit status 1
fatal: early EOF
```

And for another directory:

```
buf.exe  breaking --path Set2\Test\V1 --against .git#branch=develop
Failure: could not clone file://C:\code\.git: exit status 1
Updating files:   0% (87/104557)
...
Updating files:  21% (22228/104557)
EXEC : error : unable to create file {Here is long-path to source code file}: Filename too long
```

This repository can be checked out from origin to local machine without any problems using git witn LFS installed.
By the way,  this command works fine for a small repository created especially for tests, but failed with this huge repository with git LFS installed.

Is here some way for enabling more verbose, or even debug/trace buf.exe output for fetching more details about things what happens inside?

Thank you in advance for your help,
Sincerely, Alex

**Comment by robbertvanginkel** [comment]
Thanks for the bug report. 

Buf has a `--debug` flag that'll print out more details, but it does not currently print out what git subprocesses it creates. All git functionality is run through subprocesses though, so any windows equivalent of `strace` that shows subprocesses created could help here. 

For the "Filename too long" issue, this may be because buf needs to do a checkout of the `--against` for a comparison. It does this in a path returned by Go's `os.MkdirTemp`, although I don't have a Windows machine to check I believe this can default to a path like `C:\Users\<username>\AppData\Local\Temp`. It seems like this could be significantly longer than the `file://C:\code` where your code normally resides (according to the log).

**Comment by doriable** [comment]
Hi, a couple of quick things: the long filename issue as @robbertvanginkel noted appears to be because of the length of the filename based on the checkout, and this seems to be due to an msys issue. That being said, I ran a clean install of `git` on a Windows machine and ran some `buf breaking` commands against `googleapis` with the `--debug` flag and it did not seem to have any problems:

```
C:\Users\lokop\test\googleapis [master ≡ +1 ~0 -0 !]> ..\..\Downloads\buf-Windows-x86_64.exe breaking --against https://github.com/googleapis/googleapis.git --debug --path google
DEBUG   get_ref {"duration": "0s"}
DEBUG   get_config      {"duration": "519.7µs"}
DEBUG   get_config      {"duration": "0s"}
DEBUG   get_module_config       {"duration": "1.0475ms"}
DEBUG   parse   {"duration": "1.7146611s"}
DEBUG   get_image       {"duration": "21.0605ms"}
DEBUG   build   {"duration": "1.9475612s"}
DEBUG   build_module    {"duration": "1.9475612s"}
DEBUG   get_ref {"duration": "937.2µs"}
DEBUG   git_clone_to_bucket_copy        {"duration": "3.9148558s"}
DEBUG   git_clone_to_bucket     {"duration": "8.4949289s"}
DEBUG   get_config      {"duration": "0s"}
DEBUG   get_config      {"duration": "1.0032ms"}
DEBUG   get_module_config       {"duration": "8.4959321s"}
DEBUG   parse   {"duration": "1.3060005s"}
DEBUG   get_image       {"duration": "18.0008ms"}
DEBUG   build   {"duration": "1.3440008s"}
DEBUG   build_module    {"duration": "1.3440008s"}
DEBUG   check   {"duration": "305.9983ms", "num_files": 3541, "num_rules": 47}
DEBUG   command {"duration": "12.4127193s"}
```

I also have LFS installed for the Windows git. If you are able to provide the output of your command with `--debug` we can dig further, but for `Filename too long`, unfortunately this is based on the git client you're using and has been a known msys issue.

For comparison, my I am using `v1.0.0-rc10` for `buf` and this is my git version `git version 2.34.1.windows.1`.

**Comment by robbertvanginkel** [comment]
Can you confirm which buf version you are running? We have had issues with LFS in the past (https://github.com/bufbuild/buf/issues/424) that looked similar but this should have been resolved. Does the issue persist on the latest release ([v1.0.0-rc10](https://github.com/bufbuild/buf/releases/tag/v1.0.0-rc10))?

**Comment by qblook** [comment]
Hi @robbertvanginkel ,

`buf.exe` version `1.0.0-rc8`

// Sincerely, Alex

**Comment by qblook** [comment]
Hi @robbertvanginkel,

The same problem with `v1.0.0-rc10`

// Sincerely, Alex

**Comment by doriable** [comment]
Could you also confirm your git version? It could also be related to https://github.com/bufbuild/buf/issues/695#issuecomment-973257279

The git version I used to test on Windows was `2.34.1.windows.1`.

**Comment by qblook** [comment]
Hi @robbertvanginkel,

```
git version 2.34.1.windows.1
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
```

// Sincerely, Alex

**Comment by robbertvanginkel** [comment]
Hi @qblook 

> So, the next steps will be to stop buf.exe execution (probably, by debugger breakpoints) after git error and before removing temp dirctory for viewing more detailed output in the log-file.

Have you managed to get more details using the above, or tried the suggestion of changing `%TMP%` in https://github.com/bufbuild/buf/issues/804#issuecomment-997904151?

Unfortunately we haven't been able to reproduce so far based on the provided information. If you get a trace or reproducible case, please feel free to reopen!
