### ISSUE TITLE
FR: support for vcs repositories as explicit and implicit modules

### ISSUE THREAD

**Issue by cloneable** [bufbuild/buf#821]
Would be very useful to define, for instance, a GitHub repository, potentially with path, as dependency. The location contains `buf.yaml` and `buf.lock`. Similar to how Go modules are resolved. And if no `buf.yaml` is found, the location is loaded as an implicit module without knowledge of transitive dependencies. Those could be resolved manually, if needed.

```yaml
deps:
  - github.com/owner/repo/path/to/protos-root:tag-or-branch-or-commit
```

Right now `buf mod update` doesn't recognize github.com:

```
Failure: invalid remote "github.com", did you mean "buf.build" or "buf.build"?
```

I don't see a technical reason that prevents supporting (explicit) buf modules in remote public and private git repos and other locations.

**Comment by amckinney** [comment]
Thanks for the issue - this is one we've been asked a couple times before.

Yes, it's technically possible to support this, but it breaks down some of the strong assumptions that we can make with the BSR. To name a few:

1. If the module reference specified in a dependency is valid and successfully resolved (e.g. `buf.build/acme/weather`), then those Protobuf files are _guaranteed_ to compile in the form of a [module](https://docs.buf.build/bsr/overview#module). Arbitrary inputs like `github.com/...` are clearly not guaranteed to do the same.

2. Your dependencies aren't (and therefore _your_ module isn't) guaranteed to take advantage of _all_ of the features that the BSR will provide. For example, we want to [enforce breaking change detection](https://docs.buf.build/roadmap#enforced-linting-and-compatibility) so that we can make stronger guarantees about [dependency management](https://docs.buf.build/roadmap#solving-the-diamond-dependency-problem), but this is only possible if you have a centralized schema registry. Arbitrary remotes can't enforce the same gates that the BSR can.

3. VCS references are far more brittle than BSR references. A simple rebase in a GitHub repository (a fairly common workflow) can mutate a subset of the repository's history, which makes the references that users specify in `deps` void. The BSR isn't meant to be a fully-featured VCS, so these destructive workflows simply don't exist. Sure, it might someday be possible for users to remove references that previously existed in the BSR, but we're still deciding how we want to expose such capabilities so that we don't negatively affect this guarantee (re: [discussion](https://github.com/bufbuild/buf/issues/765)).

We might someday support a workflow like you're suggesting, but it doesn't make sense for us right now. There are too many potential negative implications surrounding a decision like this. We don't break users, so we don't want to ship something that we're not absolutely sure about.

**Comment by cloneable** [comment]
Thanks for the detailed explanations! Yes, I can see how a registry can continuously provide guarantees and on top of that offer checks in both directions of the dep graph. That's not just convenient, but valuable feedback and safety to module owners. (Plus, I noticed today the BSR is not open source and I assume that tying buf to BSR is part of the business model. That's okay. It's a valid reason not to want to support other remotes at the moment, too, as long as there's no critical mass of repos on buf.build.)

However, and no offence, the listed checks can all be done offline by `buf mod update` and `buf protoc`. I agree that arbitrary VCS locations (without module config) have very few guarantees, though this feature might help buf get more adoption. (And locations pinned to commits or something else are not as brittle as you make it sound.) Such a dependency could be marked as implicit in `buf.yaml` or better yet, there could be a `buf.repo.yaml` (or repos section in `buf.work.yaml`), which defines modules for a module-less locations and then those are added to `buf.yaml` as regular dependencies.

That said, I'm a big fan of protobuf, and would like to see its use beyond the backends of larger companies. I'm sure the BSR will be very convenient and helpful, and I don't want to distract from your v1.0 release. (Congrats!) Just please consider being more open sooner than "someday". Thank you!

**Comment by bufdev** [comment]
Just to follow up here: it was a conscious choice to not use VCS reference, as doing so actually limits the BSR ecosystem and the features that can come with it, as well as introduces brittleness - I don't see this as an extension we will end up doing. Closing this for now.
