### ISSUE TITLE
google/api/annotations.proto: no such file or directory error when hosting gRPC service on GCP CloudRun

### ISSUE THREAD

**Issue by IDispose** [bufbuild/buf#992]
I use `buf.yaml` to include the deps to googleapis. my `.ptoto` file has an `import "google/api/annotations.proto";` Everything works as expected when running `go` code locally in `vscode`. Postman is able to use server reflection without error, generate the example message and make a successful call to `gRPC` endpoint. However when the service is deployed to `GCP CloudRun` I get the error when trying to invoke the `gRPC` endpoint using `grpcurl`

```
grpcurl -H "Authorization: Bearer <TOKEN>" -proto api/example/example.proto -d '{<JSON PAYLOAD>}' example-xxx.run.app:443 example.Example/CreateItem

Failed to process proto source files.: could not parse given files: api/example/example.proto:7:8: open google/api/annotations.proto: no such file or directory

```
I dont want to copy `annotations.proto` into my repo. How do we configure to ensure GCP CloudRun is able to "get" `annotations.proto` ?

**Comment by amckinney** [comment]
From what I can tell, it's not because GCP CloudRun can't "get" `annotations.proto` - you're just not giving `grpcurl` enough information about the endpoint you're trying to call.

From the error message, `grpcurl` has "Failed to process proto source files.", which is the `-proto` flag. You should be able to fix this by using `buf build` to create a `FileDescriptorSet` that contains the transitive closure of your module's dependencies, and use the `protoset` flag instead (which is documented in the `grpcurl` docs [here](https://github.com/fullstorydev/grpcurl#protoset-files)).

Try this:
```sh
# Build the directory containing your `buf.yaml` - this assumes the current directory ('.'). 
$ buf build -o fd.bin

$ grpcurl -H "Authorization: Bearer <TOKEN>" -protoset fd.bin -d '{<JSON PAYLOAD>}' example-xxx.run.app:443 example.Example/CreateItem
```

As for how this works locally vs in CloudRun, if your program supports server reflection you shouldn't need to use `-proto` or `-protoset` at all - the server should have all of this information already. Try dropping the `-proto` flag entirely. This is also documented [here](https://github.com/fullstorydev/grpcurl#describing-elements).

Let us know if that works, and feel free to close the issue if this fixes your problem.

**Comment by amckinney** [comment]
It looks like this was also answered in Slack, so I'll mark this as resolved.

**Comment by IDispose** [comment]
This was a misunderstanding on my part. with `-protoset` I am able to make a successful call to the `gRPC` endpoint
